
<p class="newsheader_t1">Ethanol Producer Magazine</p>
<p class="newssubhead_t1">Ethanol&rsquo;s pull on gasoline weakens</p>
<p><font style="background-color:#E6EEFF">by Rick Kment </font></p>
<p><em>From the March 2010 issue</em></p>
<p>Jan. 15&mdash;The beginning of January has been brutal in the Midwest with unusually high snowfall amounts and bitterly cold temps significantly slowing supply movement from the heart of ethanol-producing country to the coasts. Most ethanol is moved by train, but due to many Midwest regions having been blanketed with 10 to 30 inches of snow and blizzard-like conditions over the holidays, travel has been ugly. But ethanol is being produced nonetheless, and at this writing, most of the major markets are back in business. The logistical challenge created significant volatility in ethanol prices throughout the country, but was short lived. The weakness in the corn market following the January USDA report sent ethanol prices into another tail spin for several days. </p>
<p>Support has been moderate to strong in the energy complex over the holidays and well into the month of January, but traders remain cautious of future upward moves due to the seemingly sluggish economic news reported at the end of January. The price spread between gasoline and ethanol markets has continued to widen with ethanol losing ground very quickly. Even though there is a potential for more demand due to the cost effectiveness of ethanol, blenders may also be just using less product at this point which could hinder overall ethanol demand in the coming weeks. Additional weakness in the stock market during the first couple weeks of February could continue to put pressure on ethanol markets and widen the gap between gasoline and ethanol. </p>
<p>Copyright&copy;  2010 Ethanol Producer Magazine. All rights reserved. <a href="http://ethanolproducer.com/article.jsp?article_id=6366" target="_blank">Original Article</a></p>
<p><em>Rick Kment is DTN's ethanol and dairy analyst.  He has more than 15 years of experience in the agribusiness and dairy industries, including five years managing his own farm and nine years working with agricultural producers and agribusinesses throughout the Midwest on animal nutrition and farm management.</em></p>
