

<p class="newsheader_t1">Midwest Producer</p>
<p class="newssubhead_t1">Market Forecaster: The April supply/demand report</p>
<p>In the April supply/demand report, USDA did not reveal any new surprises to the market. Typically, this report is a quiet report as it comes on the heels of the March 31 quarterly stocks and acreage report and just in front of the May supply/demand report. The May supply/demand report will be the first report of the year in which the USDA will make projections of the 2010 corn, soybeans and wheat crops.</p>
<p>In the April report, the USDA forecast U.S. soybean exports to hit a record 1.445 billion bushels this marketing year while the corn surplus rises to 1.899 billion bushels. The corn ending stocks figure would be the largest in four years. The strong U.S. export demand through March is projected to carry U.S. soybean exports to a record 1.445 billion bushels, 13 percent above the previous record set in 2008/09. It was the eighth month in a row USDA boosted the forecast. Ending stocks are forecast at 190 million bushels, a three-week supply, leaving U.S. supplies tight.</p>
<p>Due to U.S. livestock feeders using less corn than expected, the USDA increased ending stocks to 1.899 billion bushels, up 100 million bushels from a month ago.</p>
<p>In a surprise, USDA indicated better wheat exports and feed use, which will cut the wheat surplus, now forecast at 950 million bushels. While stocks were lowered, ending stocks are still up 45 percent from one year ago and remain the largest in a decade.</p>
<p>In world supplies, the USDA increased production estimates of soybean crops from Brazil and Argentina, the world's No. 2 and No. 3 producers, but said strong demand from China will help consume the bumper crops. Soybean production in No. 2 producer Brazil was projected at 67.5 million tonnes, up 0.5 million tonnes, and Argentine soy production was raised 1 million tonnes from last month to 54 million tonnes.</p>
<p>The USDA is forecasting South American soybeans to compete against U.S. soy exports for the rest of the marketing year as their harvest advances, however, the USDA still raised its export forecast for the United States.<br />
</p>
<p>China, the top soy importer, was forecast to buy 43.5 million tonnes of soybeans this year, up from 41.1 million tonnes last year, and 2.3 percent above last month's estimate, the USDA said.</p>
<p>Brazilian exports were raised 2.7 percent from last month to 26.3million tonnes, but exports from Argentina were unchanged from last month at 7 million tonnes. USDA also raised Brazil's corn production by 2.5 million tones from last month to 53.5 million tonnes because of good yields.</p>
<p>CORN<br />
</p>
<p>ANALYSIS</p>
<p>Corn closed the week 1 1/4 cents higher. China's state-run and private trading companies are seeking to import up to 1.0 million metric tons corn to ensure cheaper supply in south China, traders familiar with the situation said Thursday. While it makes sense to import cheaper corn from the international market to supply the southern region, it is still unclear if the government is open to the idea of large-scale imports which will drive down domestic prices and hit farm incomes in major corn growing areas in the country. But one of the state-run Chinese grain trading companies has taken long positions on the Chicago Board of Trade even though the company is still seeking import licenses from the government, a trading executive said. USDA announced a private sale of 114,300 mts of U.S. corn to Mexico last week. The weekly export sales report showed net sales of 1,357,800 MT for delivery in 2009/10 were up 64 percent from the previous week and up noticeably from the prior four-week average. Increases were reported for South Korea (616,800 MT, including 111,700 MT switched from unknown destinations and decreases of 9,700 MT), Japan (280,600 MT, including 93,200 MT switched from unknown destinations and decreases of 9,400 MT), Mexico (167,400 MT), Egypt (120,000 MT) and Guatemala (55,900 MT). This year's export profile is now at 1.4125 bb vs. the USDA forecast of 1.900 bb.</p>
<p>STRATEGY &amp; OUTLOOK</p>
<p>Producers should be 100 percent sold in cash/hedges. Producers should have purchased July options on a pullback into a support level on a portion of their 2009 production. Hedgers have sold a portion of the 2010 crop when December futures traded above $4.50. Next sales objectives for corn producers are when prices move above last spring's highs of $4.73. Producers should look at buying new crop put option protection and add to cash sales.</p>
<p>SOYBEANS</p>
<p>ANALYSIS</p>
<p>Soybeans closed the week 10 1/4 cents higher from last week. Celeres raised its soy production forecast for Brazil to 67.2 mmt, up from the 65.7 mmt it projected in March. The crop has been 75 percent harvested, compared to 61 percent at this point last year. March exports were 16% higher than last year at over 3 mmt. Celeres expects the faster shipment pace to continue through April and May. Brazil's 2009-10 soy crop is expected to be 67.3 million metric tons, the agricultural survey group of the country's census bureau, the IBGE, said Wednesday. Its previous estimate was 66.9 million tons. The National Commodities Supply Corp., or Conab, meanwhile estimated the 2009-10 soy crop at 67.4 million tons on Wednesday. Conab said Brazil produced 57 million tons in 2008-09. IBGE said the weather has been favorable in the main soy producing regions. Brazil is the world's No. 2 soy producer and exporter, behind the U.S. There were no private soybean sales last week. The weekly export sales report showed net sales of 205,700 MT for delivery in 2009/10 were up 15 percent from the previous week and 50 percent from the prior four-week average. Increases reported for Mexico (89,300 MT), Japan (45,200 MT), Morocco (30,600 MT, including 11,000 MT switched from unknown destinations), Indonesia (13,200 MT), and Colombia (7,500 MT), were partially offset by decreases for Ireland (3,300 MT). This year's export profile remains well ahead of last year's record pace at 1.3442 bb vs. the USDA forecast of 1.445 bb.</p>
<p>STRATEGY &amp; OUTLOOK</p>
<p>Producers should be 100 percent sold in cash/hedges. Producers should have purchased July options on a pullback into a support level to re-own a portion of their 2009 production. Producers have sold 2010 crop when November futures traded above $10.30 and should wait patiently for a rally to make new sales and purchase put options.</p>
<p>WHEAT</p>
<p>ANALYSIS</p>
<p>For the week, Chicago wheat closed 11 cents higher; Kansas City wheat 13 1/2 cents higher and Minneapolis wheat 12 1/4 cents higher. Winter wheat conditions continue to improve. The weekly crop conditions report showed winter wheat conditions at a five year high rating of 65 percent good to excellent. Last year's crop rating was 43 percent g/e. The Kansas wheat crop was rated 69 percent good to excellent, while Oklahoma was rated 69 percent g/e, Nebraska was rated 60 percent g/e and Texas was rated 60 percent g/e. Australian Crop Forecasters raised their estimate for Australian wheat production to 22.5 mmt, up from 21.7 mmt in January. Rains in key grain states ahead of planting could boost output and encourage more seeding. The estimate is in line with the National Australia Bank, which is calling for a 22.6 mmt crop. The USDA attach&eacute; expects a 22 mmt crop, while the Commonwealth Bank of Australia and Rabobank expect production around 20 mmt. Last week, the USDA reported a 126,000 mts wheat sale to an unknown destination. The weekly export sales report showed net sales of 323,700 metric tons for delivery in 2009/10 were down 25 percent from the previous week and 16 percent from the prior four-week average. Increases were reported for the Philippines (66,100 MT), China (55,600 MT), Taiwan (47,700 MT), Japan (45,300 MT), and South Africa (31,900 MT, including 29,900 MT switched from unknown destinations). The annual export pace remains well behind last year's pace. This year's exports stand at 787.5 mb vs. the USDA forecast of 865 mb.</p>
<p>STRATEGY &amp; OUTLOOK</p>
<p>Producers should be 100 percent sold of their 2009 crop. No reason to re-own the 2009 crop. Producers began to scale into 2010 crop sales at $6.05 off the July Kansas City contract. Next sales objectives are $6.40 and $6.75.</p>
<p>LIVE CATTLE</p>
<p>ANALYSIS</p>
<p>Live cattle ended the week $1.22 higher while feeder cattle ended $2.67 higher. Live cattle futures hit a 19 month high last week on stronger cash trade amid supportive boxed beef values. Packers continue to pay higher cash values, indicating they have positive margins and demand for beef is also strong, otherwise weekly slaughter figures would be slowing. However, packers are expected to have access to increased supplies of contracted cattle soon, which will limit the amount of cash paid by the packers. The cash cattle trade occurred in the southern Plains last week at $101.00 per cwt in Texas and Kansas, $5 higher compared with the previous week's trade of $96.00 Nebraska fed cattle traded at $162, $5.00 higher compared to the previous week's cash trade of $157. Cash feeders at the closely watched Oklahoma City auction were sharply higher this week compared to last week. USDA put 2010 beef exports up 10 million lbs and beef production up 100 million lbs. U.S. beef exports to Canada up 12 percent through March 27 due to higher Canadian dollar.</p>
<p>STRATEGY &amp; OUTLOOK</p>
<p>Producers should have price protection through a combination of options and hedges through the second quarter of 2010. Producers are strongly encouraged to hedge cattle as they are purchased. Producers especially need to have April covered as there will be a large amount of market ready cattle in April. Feed costs should be covered during this price break in corn futures ahead of the growing season.</p>
<p>LEAN HOGS</p>
<p>ANALYSIS</p>
<p>Lean hogs closed the week $2.15 higher. Last week, lean hog futures closed higher once again, following strength from the cash market and spillover strength from live cattle. Lean hogs are benefiting from large scale fund buying as well as better fundamentals, including strong demand and higher cash trade. Commercial accounts, normally not the most trustworthy of indicators in the hog market, continue to hold a major net short position in the market. The average Iowa-Minnesota hog weight for last week was estimated at 270.2 lbs versus 270.0 lbs previous week and 269.1 lbs last year. USDA put 2010 pork exports down 140 million lbs and pork production off 100 million lbs. U.S. pork exports to Canada up 43 percent through March 27 due to higher Canadian dollar.</p>
<p>STRATEGY &amp; OUTLOOK</p>
<p>Producers should now be hedged or covered the downside with put options if producers want to leave the upside open. Producers should be 100 percent covered through the second quarter of 2010 with either futures or options or a combination. Price levels should be profitable and extending coverage at profitable levels makes sense. Producers should covered their meal needs now as prices are near the bottom of the trading channel.</p>
<p>Producers should also cover their corn needs through the first and second quarters of 2010 as corn prices are coming under seasonal weakness.</p>
<p>News from Reuters News, Bloomberg News, Dow Jones Newswires and Red River Farm Network.</p>
<p>The Kansas City Board of Trade's Hard Red Winter Wheat futures trading volume for March was the third largest in the exchange's history for the calendar month. A total of 273,549 HRW wheat futures contracts were traded during the month of March, behind only March 2006 and 2009 trading volumes of 363,605 contracts and 280,459 contracts, respectively.</p>
<p>Continuing a pattern of strong year-over-year volume and open interest growth, MGEX (Exchange) today announced March 2010 total futures and options volume grew 20 percent over the same period last year to 92,397. Total open interest increased 57 percent over March 2009. Volume for the Exchange's flagship Hard Red Spring Wheat (HRSW) futures contract increased 18 percent in March 2010 to 89,969. HRSW options volume enjoyed a 134 percent increase. Additionally, trading of the MGEX Soft Red Winter Wheat Index (SRWI) continued, adding to the overall volume increase.</p>
<p>News reports from Brazil indicate farmers in Mato Grosso are considering legal action against Monsanto. The Association of Soya and Corn Producers is suing to determine if the royalty fee paid by soybean producers is actually due. The growers also want to know the patent's validity period. Approximately half the soybeans in northern Mato Grosso are biotech varieties.</p>
<p>China's government started stockpiling frozen pork today to stop prices falling, China Central Television said on its main evening news bulletin. The purchasing is being led by the National Development and Reform Commission, the report said, citing the economic planning agency. Pork prices have fallen for the past 12 weeks, according to the report.</p>
<p>For the first time ever, farmers in the state of Kansas are projected to plant more corn and soybeans than wheat. The loss of acres illustrates a nationwide drop in wheat plantings attributed to weak prices and wet weather last autumn that prevented farmers from planting. For the 2010-11 crop year, growers are expected to plant 8.8 million acres of corn and soybeans, up from 7.8 million last year, and 8.6 million acres of wheat, down from 9.3 million the previous year, according to USDA's annual planting intentions report. Nationwide, total wheat acres are estimated at 53.8 million acres, down from 59.1 million in the 2009-10 crop year.</p>
<p>A yield-reducing fungus is attacking winter wheat fields across the U.S. Deep South and plant disease specialists are concerned it could soon spread north to Kansas, the nation's top-producing wheat state. The disease, called stripe rust, is caused by the fungus Puccinia striiformis and often causes yield losses of around 40 percent on susceptible wheat varieties. It can destroy fields outright if not treated quickly with chemical fungicides. The pathogen ? which is spread by the wind and thrives in cool, damp weather such as what has predominated this spring ? has been found in wheat throughout the state of Louisiana and has even infected popular varieties thought to be resistant.</p>
<p>USDA is suspending a program that supports farm exports as part of an agreement with Brazil to end a trade dispute. The USDA's GSM-102 Export Credit Guarantee Program will be reinstated under new fee rates after rules are revised, the department said in an e-mail. Brazil had complained about the program to the World Trade Organization in a case that triggered as much as $830 million in sanctions against U.S.</p>
<p>Midwest Market Solutions is the leading edge in commodity marketing and trading. Midwest Market Solutions was established in March 2002 and is a full-service commodity brokerage and marketing advisory service, clearing through R.J. O'Brien. The firm specializes in individual trading strategies for the investor, personalized marketing programs for individual farm operations as well as full-service and discount broker services. The firm is located in Yankton, S.D., and is committed to providing clients with the best information and service as possible. Midwest Market Solutions provides clients with written newsletters, trade research and hedging as well as trading advice.</p>
<p>Brian Hoops is president and senior market analyst of Midwest Market Solutions, Inc. Brian can be heard on radio stations across the country including: WNAX, WHO, and the Red River Farm Network.. <font style="background-color:#E6EEFF">Brian can also be heard daily on the DTN doing his own grain market commentary program as well as the Minneapolis Grain Exchange marketing hotline and the University of Illinois commodity wrap up program. </font>Brian also writes several newsletters that are published throughout the Plains and the Midwest, covering Iowa, Minnesota, North and South Dakota, Nebraska, Kansas, Montana, Wyoming and Idaho. Brian has been quoted in the Wall Street Journal, Bloomberg and Dow Jones newswires and U.S. Farm Report.</p>
<p>The Market Insider Newsletter is an opinion only; expressed with the best intentions, but not guaranteed. The thoughts expressed and the data from which they are drawn are believed to be reliable but cannot be guaranteed because of their complexities and their reference to the future. Neither the information presented nor any of the opinions expressed constitute a solicitation by Midwest Market Solutions, Inc. for the purchase or sale of any commodities. Any opinions expressed herein are subject to change without notice. Any republication or use of this information without the express written permission of Midwest Market Solutions, Inc. is strictly prohibited. The risk of loss in trading commodity futures may be substantial and therefore may not be suitable for the recipients of this information. Those acting on this information are responsible for their own actions. Midwest Market Solutions reserves the right to change orders, stops or take profits as market conditions warrant during the trading session.</p>
<p>Midwest Market Solutions does not necessarily take every trade recommendation listed herein. Hypothetical performance results have many inherent limitations, some of which are described below. No representation is being made that any account will or is likely to achieve profits or losses similar to those shown in fact there are frequently sharp differences between hypothetical performance results and the actual results subsequently achieved by any particular trading program. One of the limitations of hypothetical performance results is that they are generally prepared with the benefit of hindsight. In addition, hypothetical trading does not involve financial risk and no hypothetical trading record can completely account for the impact of financial risk in actual trading. For example, the ability to withstand losses or adhere to a particular trading program in spite of trading losses is material points which can also adversely affect actual trading results. There are numerous other factors related to the markets in general or to the implementation of any specific trading program, which cannot be fully accounted for in the preparation of hypothetical performance, results and all of which can adversely affect actual trading results.</p>
<p>Copyright&copy;  Midwest Producer. All rights reserved. <a href="http://www.midwestproducer.com/articles/2010/04/12/news/markets/markets20.txt" target="_blank">Original Article</a></p>
