

<p class="newsheader_t1">FarmPolicy.com</p>
<p class="newssubhead_t1">Climate Issues; Biotechnology; Animal Agriculture; Competition; Farm Bill; Sugar; Food Safety; and CFTC Issues</p>
<p>Darren Goode reported yesterday at the NationalJournal Online that, &ldquo;Senate Majority Leader Harry Reid, D-Nev., today said that taking up a climate and energy strategy could be on his to-do list before Memorial Day. When asked by a reporter specifically on climate change legislation, Reid said, &lsquo;We have to &mdash; we&rsquo;re going to see when we can move to energy.&rsquo;</p>
<p>&ldquo;Reid spokesman Jim Manley clarified that Reid was referring to the climate and energy bill being put together by Senate Foreign Relations Chairman John Kerry, D-Mass., and Sens. Lindsey Graham, R-S.C., and Joe Lieberman, I/D-Conn. Lieberman has predicted a bill to hit the Senate floor in June and that debate may roll into July.&rdquo;</p>
<p>Darren Samuelsohn of Climatewire reported yesterday at The New York Times Online that, &ldquo;The Senate&rsquo;s top Democrat said yesterday he is still dedicated to spending valuable floor time this year on comprehensive climate and energy legislation, but the three sponsors of the plan may have to go member-by-member in order to deliver a package capable of mustering 60 votes.&rdquo;</p>
<p>The article pointed out that; &ldquo;Kerry, Graham and Lieberman are planning to release their bill (which is expected to place different emission limits on different sectors of the economy and expand domestic oil, gas and nuclear power production) next week to coincide with the 40th anniversary of Earth Day on April 22. &lsquo;There&rsquo;s some issues we&rsquo;re closing out, discussing,&rsquo; Lieberman said. &lsquo;But we&rsquo;re making progress, and as far as I&rsquo;m concerned, we&rsquo;re still on track to introduce next week.&rsquo;&rdquo;</p>
<p>&ldquo;The biggest subset of fence sitters includes 10 Democrats from states with a heavy reliance on coal, oil, natural gas and trade-sensitive industries. Senate aides acknowledge that Kerry, Graham and Lieberman are building their bill around this core group of Democrats, including Sens. Sherrod Brown of Ohio, Debbie Stabenow of Michigan, Mark Begich of Alaska, Robert Byrd of West Virginia and Mary Landrieu of Louisiana,&rdquo; the article said.</p>
<p>Mr. Samuelsohn added that, &ldquo;One key debate involves fence-sitting Sens. Maria Cantwell (D-Wash.) and Susan Collins (R-Maine). The duo have proposed a competing bill, S. 2877, aimed at circumventing a trillion-dollar carbon trading market. Kerry said he plans to take many of their ideas and fold them into his measure, and some environmentalists have a hard time envisioning Cantwell and Collins opposing a final climate bill.&rdquo;</p>
<p>&ldquo;Another crop of fence sitters include senators who have shied from the climate spotlight, including Sens. Olympia Snowe (R-Maine), Claire McCaskill (D-Mo.) and Mark Pryor (D-Ark.).&rdquo;</p>
<p>Meanwhile, Reuters writer Richard Cowan reported yesterday that, &ldquo;Some prominent Republican senators expressed openness on Tuesday to a U.S. climate change bill that might be introduced next week and that would need bipartisan support to have any chance of advancing.</p>
<p>&ldquo;Senator Lamar Alexander, a member of the Republican leadership in the Senate, praised the sector-by-sector approach in a compromise bill aimed at reducing emissions of carbon dioxide and other greenhouse gases blamed for global warming.&rdquo;</p>
<p>&ldquo;Republican Senator Scott Brown, whose election in January robbed Democrats of their 60-seat supermajority, told Reuters, &lsquo;I&rsquo;m open to reading anything that&rsquo;s being proposed&rsquo; for climate change legislation,&rdquo; the article noted.</p>
<p>Jordan Fabian indicated yesterday at The Hill&rsquo;s Energy and Environment Blog that Sen. Kerry met yesterday with Rep. Henry Waxman (D-Calif.) and Ed Markey (D-Mass.), &ldquo;two House Democrats who helped pass the lower chamber&rsquo;s legislation.&rdquo;</p>
<p>And Simon Lomax reported yesterday at Bloomberg that, &ldquo;President Barack Obama&rsquo;s plan to quickly replace retiring Supreme Court Justice John Paul Stevens won&rsquo;t prevent the U.S. Senate from taking up climate-change legislation before elections this year, Senator John Kerry said.</p>
<p>&ldquo;The Senate confirmation process for Obama&rsquo;s nominee to replace Stevens &lsquo;is an important debate, but we&rsquo;re capable of doing more than one thing at the same time around here,&rsquo; Kerry told reporters yesterday in Washington.&rdquo;</p>
<p>In an editorial item posted on Monday at Roll Call Online (&ldquo;Cap-and-Trade Will Hurt Economy&rdquo;), Sen. Kit Bond (R-Missouri) stated that, &ldquo;Too many Americans are out of work or need better-paying jobs. While Congress and the president have been distracted on other issues, our nation&rsquo;s unemployment remains too high and prospects for recovery too dim. We must return to a real jobs agenda that neither raises taxes nor kills existing jobs.</p>
<p>&ldquo;When the administration or its supporters do mention jobs, it is usually sheep&rsquo;s clothing hiding a wolf. I am talking about cap-and-trade bill proponents trying to hide the pain of their proposals behind a green jobs curtain. But the American people are duly skeptical of the potential for green jobs to overcome the burden of new energy taxes or the existing jobs that will be lost.&rdquo;</p>
<p>Also yesterday, Phil Izzo, reported at the Real Time Economics Blog (The Wall Street Journal) that, &ldquo;Robert W Hahn and Robert N. Stavins look at the political appeal of cap and trade. Are cap-and-trade schemes working? This column presents a summary of eight existing schemes arguing that half meet the independence property whereby the initial allocation of property rights does not affect the environmental or social outcome and the scheme is cost-effective. This success is a contrast with other policy proposals where political bargaining reduces the effectiveness and drives up cost.&rdquo;</p>
<p>And Reuters writers Tom Doggett and Timothy Gardner reported yesterday that, &ldquo;Government ministers from more than 30 countries in the Americas will meet in Washington this week for a two-day conference as part of an Obama administration effort to boost cooperation on energy security and climate change.</p>
<p>&ldquo;The conference is supposed to build on the goals of the Energy and Climate Partnership of the Americas that was launched by President Barack Obama and leaders of other countries one year ago.&rdquo;</p>
<p>Biotechnology</p>
<p>Andrew Pollack reported yesterday at The New York Times Online that, &ldquo;Genetically engineered crops have provided &lsquo;substantial&rsquo; environmental and economic benefits to American farmers, but overuse of the technology is threatening to erode the gains, a national science advisory organization said Tuesday in a report. [Full report available here, additional information regarding the report is available here].</p>
<p>&ldquo;The report is described as the first comprehensive assessment of the impact of genetically modified crops on American farmers, who have rapidly adopted them since their introduction in 1996. The study was issued by the National Research Council, which is affiliated with the National Academy of Sciences and provides advice to the nation under a Congressional charter.</p>
<p>&ldquo;The report found that the crops allowed farmers to either reduce chemical spraying or to use less harmful chemicals. The crops also had lower production costs, higher output or extra convenience, benefits that generally outweighed the higher costs of the engineered seeds.&rdquo;</p>
<p>The Times article added that, &ldquo;But Dr. Ervin [the chairman of the committee that wrote the report], a professor of environmental management and economics at Portland State University in Oregon, warned that farmers were jeopardizing the benefits by planting too many so-called Roundup Ready crops. These crops are genetically engineered to be impervious to the herbicide Roundup, allowing farmers to spray the chemical to kill weeds while leaving the crops unscathed.</p>
<p>&ldquo;Overuse of this seductively simple approach to weed control is starting to backfire. Use of Roundup, or its generic equivalent, glyphosate, has skyrocketed to the point that weeds are rapidly becoming resistant to the chemical. That is rendering the technology less useful, requiring farmers to start using additional herbicides, some of them more toxic than glyphosate.&rdquo;</p>
<p>Scott Kilman reported in today&rsquo;s Wall Street Journal that, &ldquo;Biotechnology is controversial among environmental activists, who worry that pollen from genetically modified crops can spread unwanted traits to organic farms. But the independent scientific group concluded that genetically modified crops on balance do less damage to the environment than conventional crops.&rdquo;</p>
<p>&ldquo;The authors of the report warned, however, that farmers would undermine the effectiveness of herbicide-tolerant crops if they didn&rsquo;t begin using them more prudently. Several weeds in the Southern U.S. have already developed resistance to glyphosate, apparently because of repeated applications,&rdquo; the Journal article said.</p>
<p><font style="background-color:#E6EEFF">DTN Ag Policy Editor Chris Clayton reported yesterday that, &ldquo;The focus of the study was to examine the effect of biotechnology on farm economics and sustainability. Reducing runoff into waterways, &lsquo;may be the single-largest contribution of GE (genetically engineered) crops&rsquo; in improving the environment and creating more sustainable production practices, said one of the researchers, LaReesa Wolfenbarger, a biology professor at the University of Nebraska at Omaha, at a press conference broadcast over the internet.&rdquo;</font></p>
<p><font style="background-color:#E6EEFF">The DTN article added that, &ldquo;Further, at least two pests have developed resistance to bacillus thuringiensis, or Bt corn and cotton varieties, though the economic and agronomic impacts of those resistant pests have been minimal thus far.</font></p>
<p>&ldquo;Researchers recommended stakeholder groups and companies more aggressively examine the issues of increased weed resistance to glyphosate and other herbicides that may have less impact on the environment.&rdquo;</p>
<p>Philip Brasher noted yesterday at The Des Moines Register Online that, &ldquo;Last year, farmers used biotech seed for 86 percent of the corn, 91 percent of the soybeans and 88 percent of the cotton they planted nationwide last year, according to the Agriculture Department.</p>
<p>&ldquo;John Heisdorffer, who farms west of Washington, Ia., is typical of many growers. He said saves on fuel and herbicide costs because he needs less of both, because Roundup replaces several chemicals he used previously and doesn&rsquo;t have to be applied as frequently as they did. He also gets a discount of as much as $4 an acre on crop insurance because the biotech varieties are considered more reliable.&rdquo;</p>
<p>Animal Agriculture</p>
<p>Leora Broydo Vestel reported yesterday at the Green Inc. Blog (The New York Times) that, &ldquo;The board of directors of McDonald&rsquo;s has recommended that the company&rsquo;s shareholders vote against a proposal to require that 5 percent of the eggs purchased for the chain&rsquo;s restaurants in the United States be the cage-free variety.</p>
<p>&ldquo;The proposal was advanced by the Humane Society of the United States.</p>
<p>&ldquo;Some major fast food companies, including Burger King, Subway and Wendy&rsquo;s, and the retailers Wal-Mart and Trader Joe&rsquo;s, have already made some level of commitment to purchasing or selling cage-free eggs.</p>
<p>&ldquo;But the McDonald&rsquo;s board said on Friday that the science was not there to support a switch.</p>
<p>&ldquo;&lsquo;As we have examined this issue over the years, we have determined that there is no agreement in the global scientific community about how to balance the advantages and disadvantages of laying hen housing systems,&rsquo; it said in a proxy statement.&rdquo;</p>
<p>Competition</p>
<p>The AP reported today that, &ldquo;Federal regulators are set to release the most sweeping antitrust rules covering the meat industry in decades, potentially altering the balance of power between meat companies and the farmers who raise their animals.</p>
<p>&ldquo;Activists, farmers and meat industry officials have been anxiously awaiting the new rules, which will be released this spring for public comment and are set to take effect this summer. The regulations are seen as a kind of litmus test for the Obama administration and how far it will go in regulating competition in the meat industry.</p>
<p>&ldquo;At issue is how much power farmers have as they produce cattle, hogs and chickens for large companies such as JBS SA, Smithfield Farms and Tyson Foods. The new rules will govern how meatpackers buy their cattle on an open market and what demands poultry companies can make on the independent contractors who raise their chickens.&rdquo;</p>
<p>The article noted that, &ldquo;The 2008 Farm Bill required updated rules but left the specifics to the U.S. Department of Agriculture. Farm state lawmakers such as Sen. Tom Harkin, D-Iowa, had long been concerned a lack of competition among meat companies was driving down prices farmers were paid for their cattle and poultry.&rdquo;</p>
<p>Farm Bill</p>
<p>A news release issued yesterday by the American Soybean Association (ASA) stated that, &ldquo;[ASA] is already gearing up for the 2012 Farm Bill by establishing a 2012 Farm Bill Working Group to develop policies key to the future of all U.S. soybean growers. ASA producer-leaders recently met with House Agriculture Committee Chairman Collin Peterson (D-MN) to discuss his plans to hold preliminary hearings on the 2012 Farm Bill in Washington beginning in April.</p>
<p>&ldquo;&lsquo;In establishing the working group, I attempted to identify members who will bring experience in key farm policy, crop and revenue insurance, bioenergy, agricultural research, and trade, and perspectives from all soybean production areas,&rsquo; said ASA President Rob Joslin, a soybean producer from Sidney, Ohio. &lsquo;I&rsquo;ve also included past leaders who have been involved in previous farm bill debates to ensure that ASA is fully prepared to offer and advocate meaningful policies.&rsquo;&rdquo;</p>
<p>An update yesterday from the Federal Reserve Bank of Kansas City stated that, &ldquo;In 2010, many farmers will again need to decide whether to remain in the 2002 Farm Bill program (DCP), which protects farm revenues against price declines, or to enroll in the 2008 farm program (ACRE) that protects against revenue shortfalls caused by falling prices or low yields. In the latest issue of &lsquo;The Main Street Economist,&rsquo; Brian Briggeman of the Federal Reserve Bank of Kansas City and Jody Campiche of Oklahoma State University examine how enrollment in ACRE might affect future farm profitability, farmland values, and costs to the taxpayer. The article is available here.</p>
<p>And an update posted on Friday at the Food and Agricultural Policy Research Institute (FAPRI) Online noted that, &ldquo;The FAPRI ACRE Risk Management (FARM) Tool has been updated for the 2010 Average Crop Revenue Election (ACRE) signup. The FARM Tool was designed to be an educational aide to help producers make sense of the ACRE program.&rdquo;</p>
<p>Sugar</p>
<p>Carolyn Cui, Bill Tomson and Ilan Brat reported in today&rsquo;s Wall Street Journal that, &ldquo;The U.S. Department of Agriculture indicated it will allow a small increase in U.S. sugar imports this year, a decision that is likely to do little to quell complaints from confectioners and processors about tight supplies.</p>
<p>&ldquo;Agriculture Secretary Tom Vilsack said Tuesday that the department would make &lsquo;some adjustment&rsquo; to the sugar quota, which has been in place for decades. Mr. Vilsack said it could be raised by about 24%, or as much 300,000 short tons, from the 1.23 million short-ton level, an increase he described as not significant.&rdquo;</p>
<p>Food Safety</p>
<p>Peter Eisler reported yesterday at the USA Today Online that, &ldquo;Beef containing harmful pesticides, veterinary antibiotics and heavy metals is being sold to the public because federal agencies have failed to set limits for the contaminants or adequately test for them, a federal audit finds.</p>
<p>&ldquo;A program set up to test beef for chemical residues &lsquo;is not accomplishing its mission of monitoring the food supply for &hellip; dangerous substances, which has resulted in meat with these substances being distributed in commerce,&rsquo; says the audit by the U.S. Department of Agriculture&rsquo;s Office of Inspector General.&rdquo;</p>
<p>The article noted that, &ldquo;The testing program for cattle is run by the USDA&rsquo;s Food Safety and Inspection Service (FSIS), which also tests meat for such pathogens as salmonella and certain dangerous strains of E. coli. But the residue program relies on assistance from the Environmental Protection Agency, which sets tolerance levels for human exposure to pesticides and other pollutants, and the Food and Drug Administration, which does the same for antibiotics and other medicines.</p>
<p>&ldquo;Limits have not been set by the EPA and FDA &lsquo;for many potentially harmful substances, which can impair FSIS&rsquo; enforcement activities,&rsquo; the audit found.&rdquo;</p>
<p>CFTC Issues</p>
<p>Damian Paletta and Scott Patterson reported in today&rsquo;s Wall Street Journal that, &ldquo;Senate Democrats, resisting a last-ditch lobbying push from big Wall Street firms, are moving toward a sweeping revamp of financial regulation that would squeeze banks&rsquo; lucrative derivatives-trading business.</p>
<p>&ldquo;Wall Street giants Goldman Sachs Group Inc., J.P. Morgan Chase &amp; Co. and Morgan Stanley had been pressing hard in recent days to dilute provisions of the bill that would change the rules for derivatives trading. But the Obama administration, which has made this one of its priorities for the financial-regulatory bill, has pushed back hard and appears to be succeeding. That&rsquo;s drawing Republican complaints that the pending rewrite of the rules of finance will put the economy at risk.&rdquo;</p>
<p>The Journal article stated that, &ldquo;Derivatives are financial instruments that derive their value from the movement of something else&mdash;for instance, the price of wheat or other commodities, or the level of interest rates. In recent years, a strain of derivatives known as credit-default swaps (in effect, a bet on a borrower&rsquo;s ability to repay a debt) has exploded. Derivatives figured in the global financial crisis, though their precise role is a subject of debate.</p>
<p>&ldquo;The bankers&rsquo; lobbying has focused on the Senate Agriculture Committee, which Wall Street hoped would produce a friendlier bill than an alternative from the Senate Banking Committee. But it became clear Tuesday that the Agriculture Committee&rsquo;s chairman, Arkansas Democrat Blanche Lincoln, is now expected to introduce a bill with provisions that bankers oppose and the White House supports.&rdquo;</p>
<p>John Bresnahan and Carrie Budoff Brown reported yesterday at Politico that, &ldquo;A new proposal by Senate Agriculture Committee Chairwoman Blanche Lincoln would require sweeping changes to the $450 trillion derivatives market, including forcing big banks to spin off &lsquo;swaps desks&rsquo; that handle the complex financial instruments &mdash; a more aggressive approach than either the White House or other congressional committees have advocated so far, according to the Arkansas Democrat and her aides.&rdquo;</p>
<p>The article noted that, &ldquo;Lincoln, who is briefing Democrats on the Agriculture Committee on Tuesday afternoon about her initiative, is focusing on four main areas:</p>
<p>&ldquo;- first, Lincoln will propose regulating foreign currency swaps, an action even the Treasury Department has opposed;</p>
<p>&ldquo;- second, Lincoln would bar any &lsquo;major swaps dealers,&rsquo; including big banks, from receiving federal financial assistance in the event of a market meltdown;</p>
<p>&ldquo;- third, the Arkansas Democrat would require dealers to consider their &lsquo;fiduciary duty&rsquo; to all governmental agencies, pension plans, endowments or retirement funds during any transaction;</p>
<p>&ldquo;- and fourth, swaps dealers or other traders in the complex financial instruments would be open to fraud actions brought by federal government, if they engage in a transaction with another party knowing the deal could be used to defraud other investors or the public.&rdquo;</p>
<p>Damian Paletta noted yesterday at the Washington Wire Blog (The Wall Street Journal) that, &ldquo;Sen. Saxby Chambliss blasted the White House, Treasury Secretary Timothy Geithner, and Commodity Futures Trading Commission Chairman Gary Gensler, saying they are trying to scuttle a bipartisan bill to oversee derivatives trading. Chambliss, a Georgia Republican, is working on with Sen. Blanche Lincoln, the Arkansas Democrat who chairs the Senate Agriculture Committee. [Full statement by Sen. Chambliss available here].</p>
<p>&ldquo;Chambliss&rsquo;s comments came in response to a Wall Street Journal article today on the White House&rsquo;s objections to their potential deal.&rdquo;</p>
<p>&ldquo;The White House offered a quick response. &lsquo;The president has been clear that he will fight efforts to weaken the Wall Street reform bill moving through Congress and he remains hopeful that Republicans in Congress will join us in pushing for a strong bill that holds Wall Street accountable and will put in tough rules to protect consumers,&rsquo; said White House spokeswoman Jen Psaki. &lsquo;Anything less is unacceptable.&rsquo;&rdquo;</p>
<p>Keith Good</p>
<p>Copyright&copy;  FarmPolicy.com. All rights reserved. <a href="http://www.farmpolicy.com/?p=2125" target="_blank">Original Article</a></p>
