

<p class="newsheader_t1">FarmPolicy.com</p>
<p class="newssubhead_t1">Farm Bill Hearing; Biofuels; and Climate Issues     </p>
<p>Farm Bill Hearing</p>
<p>Reuters writer Charles Abbott reported yesterday that, &ldquo;Congress should ban sugary sodas from the $58 billion-a-year U.S. food stamp program as a step to combat the obesity crisis, the House Agriculture Committee was told on Thursday.</p>
<p>&ldquo;Wellesley College professor and food expert Rob Paarlberg suggested the ban during a hearing to review the 2008 farm law, which includes food stamps as well as crop subsidies. Food stamps help low-income people buy food. One in eight Americans receives food stamps.&rdquo;<br />
</p>
<p>Yesterday&rsquo;s article stated that, &ldquo;&lsquo;I would argue caloric soda should be made ineligible for purchase under SNAP, like tobacco and alcohol,&rsquo; said Paarlberg, using the new name for food stamps, the Supplemental Nutrition Assistance Program. He later said sugary sodas are &lsquo;a huge part of the obesity problem.&rsquo;</p>
<p>&ldquo;Committee chairman Collin Peterson told reporters, &lsquo;It clearly is something we need to look at.&rsquo;</p>
<p>&ldquo;&lsquo;We need to look at what effect, if any, we&rsquo;re having on the obesity situation. Is the SNAP program contributing to that?&rsquo; said Peterson. &lsquo;That&rsquo;s the first question, before we talk anything about money.&rsquo;&rdquo;</p>
<p>(FarmPolicy.com Note: To listen to extended comments on this issue by Dr. Paarlberg from yesterday&rsquo;s hearing, just click here (MP3-5:02); also, an entire audio rebroadcast of yesterday&rsquo;s hearing is available for replay or download here.)</p>
<p>Mr. Abbott noted that, &ldquo;First Lady Michelle Obama unveiled a 70-point plan on Tuesday to reduce childhood obesity rates within a generation. The report called for larger enrollment in public nutrition programs, putting healthier foods in school meals and encouraging Americans to eat more fruits and vegetables.&rdquo;</p>
<p>Philip Brasher reported yesterday at The Green Fields Blog (The Des Moines Register) that, &ldquo;The White House plan for attacking childhood obesity ran into resistance today from a key player on Capitol Hill. The chairman of the House Agriculture Committee, Rep. Collin Peterson, said he doesn&rsquo;t think that increasing the number of people on food stamps or subsidizing fruits and vegetables are solutions to obesity.</p>
<p>&ldquo;The White House plan, released on Tuesday, called for expanding enrollment in food stamps and using the next farm bill to expand production of fruits and vegetables. The plan sets a target of increasing fruit and vegetable supplies 70 percent by 2020.</p>
<p>&ldquo;&lsquo;I do not believe the solution to obesity is spending more money on fruits and vegetables,&rsquo; the Minnesota Democrat told reporters during a break in a hearing on farm policy.&rdquo;</p>
<p>Mr. Brasher explained that, &ldquo;The White House was not specific in how fruit and vegetable production should be subsidized. An Iowa State University economist, Bruce Babcock, warned Peterson&rsquo;s committee against directly subsidizing farmers, saying that would cause growers&rsquo; prices to crash. It would be better, he said, to subsidize transportation or other costs necessary to get produce to markets where fresh produce is now hard to get.&rdquo;</p>
<p>(FarmPolicy.com Note: To listen to some of Dr. Babcock&rsquo;s analysis on this issue, which was provided in a response to a question by Rep. Kathleen Dahlkemper (D-Penn.), just click here MP3- 2:11.))</p>
<p>Jerry Hagstrom reported yesterday at DTN (link requires subscription) that, &ldquo;[Chairman] Peterson also said he does not understand why anti-hunger advocates keep saying there is a simultaneous problem of hunger and obesity.</p>
<p>&ldquo;Jean Kinsey, a University of Minnesota economics professor, replied that when people are hungry &lsquo;they tend to eat what is available,&rsquo; and that those foods are usually cheap, high in fat, dense in calories and nutritionally poor. Kinsey said that the most frequent question she gets is &lsquo;Why doesn&rsquo;t our government subsidize the production of fruits and vegetables like (or instead of) corn and soybeans?&rsquo;</p>
<p>&ldquo;Peterson told the reporters, &lsquo;I do not believe the solution to obesity is spending more money on fruits and vegetables. That might be part of the solution. I don&rsquo;t know where we get the money to do that.&rsquo;&rdquo;</p>
<p>(FarmPolicy.com Note: To listen to remarks on this issue by Chairman Peterson from yesterday&rsquo;s hearing, just click here (MP3-5:27). As a side note, on the issue of farm payments, Chairman Peterson indicated in a prelude to his comments on nutrition issues that the 10% of farmers who are getting 60% of farm payments generate 80% of production. The fact that payments follow production makes sense, he noted.)</p>
<p>Mr. Hagstrom added that, &ldquo;Tied to that notion of eating more fruits and vegetables, Neil Hamilton of Drake University also disputed recent criticism of the Obama administration&rsquo;s &lsquo;Know Your Farmer, Know Your Food&rsquo; program as aimed at hobby farmers and affluent consumers. Hamilton called for continuation of the program, saying it helped create farmers markets where millions of Americans can exercise their preference to buy fresh food from local farmers whose earnings stay in the community.&rdquo;</p>
<p>In a related article discussing a separate issue related to soda, Tim Craig reported in today&rsquo;s Washington Post that, &ldquo;The beverage industry is mounting an expensive campaign to derail a D.C. Council proposal for a citywide soda tax, setting up a two-week showdown between some city grocers and health advocates over how best to curb childhood obesity rates.</p>
<p>&ldquo;To pay for a council initiative requiring city schools to serve more fresh fruit and vegetables to students, council member Mary M. Cheh (D-Ward 3) has proposed a 1-cent-per-ounce tax on bottled and canned soda that contains sugar. Diet soda would be exempt.&rdquo;</p>
<p>Meanwhile, Gannett writer Maureen Groppe reported yesterday that, &ldquo;Congress should replace direct payments to farmers with a more effective and appropriate safety net, Purdue University agriculture economist Otto Doering told lawmakers Thursday.</p>
<p>&ldquo;Doering said direct payments don&rsquo;t address the volatility of crop prices, are viewed negatively by the public and are expensive.</p>
<p>&ldquo;&lsquo;The goal of income parity of farm people versus urban people has been achieved,&rsquo; Doering said during a House hearing on agriculture policy. &lsquo;Our chief concern now should be volatility.&rsquo;&rdquo;</p>
<p>The article indicated that, &ldquo;[Doering] advocated a safety net tied to crop prices that would be balanced with the crop insurance and disaster programs.</p>
<p>&ldquo;Congress has undercut the crop insurance program because of its willingness to hand out disaster assistance, Doering said.&rdquo;</p>
<p>In a separate issue that came up at yesterday&rsquo;s hearing, Philip Brasher reported yesterday at The Green Fields Blog that, &ldquo;[Neil Hamilton, who runs the Agricultural Law Center at Drake University, has] got the ear of Agriculture Secretary Tom Vilsack and is a nationally recognized proponent of local food initiatives as a way of getting more farmers on the land and serving the growing demand for locally produced foods. The Obama administration&rsquo;s emphasis on local foods and helping small-scale farmers has irked many in conventional agriculture, including in Iowa, the No. 2 recipient of federal farm subsidies after Texas. &lsquo;If we&rsquo;re going to have a prospering main street &hellip; it&rsquo;s not going to be because someone has a lifestyle as a farmer,&rsquo; said Rep. Jerry Moran, R-Kansas.</p>
<p>&ldquo;Hamilton, who probably fits Moran&rsquo;s definition of a lifestyle farmer, stood his ground. Under existing farm policy, rural populations have declined and the number of farms has been dropping, he said. At another point in the hearing, he said that the small-scale farmers who serve farmers markets in cities such as Des Moines are filling a demand and &lsquo;taking urban money back&rsquo; to rural areas, Hamilton said. He and his wife raise vegetables for sale to local restaurants near Waukee. He&rsquo;s founder the Slow Food Des Moines chapter.</p>
<p>&ldquo;Enter another Iowan, Democratic Rep. Leonard Boswell, to play peacemaker. &lsquo;There is not a threat to production agriculture,&rsquo; he said. &lsquo;There&rsquo;s room for both.&rsquo;&rdquo;</p>
<p>(FarmPolicy.com Note: To listen to more detailed comments from Rep. Moran regarding the importance of production agriculture in rural America, just click here (MP3-5:00.))</p>
<p>Secretary of Agriculture Tom Vilsack was a guest on yesterday&rsquo;s AgriTalk Radio Program with Mike Adams, and the subject of USDA farm policy focus with respect to production agriculture and the &ldquo;Know Your Farmer&rdquo; program were discussed. To listen to an audio clip from yesterday&rsquo;s AgriTalk show, just click here (MP3-5:44).</p>
<p>In other policy developments, Bob Meyer reported yesterday at Brownfield that, &ldquo;U.S. Trade Representative Ron Kirk was in Southwestern Wisconsin Thursday to tour a Foremost Farms USA cheese plant and visit with dairy producers. The Ambassador talked about the need to complete pending free trade agreements with Panama, Columbia and South Korea and what those agreements would mean for dairy. &lsquo;With Korea for example, there are some estimates that our dairy exports could increase by as much as $245 million.&rsquo; He says Panama and Columbia could add around $25 million each. Kirk says he would like to move the deals forward within the next twelve months but realizes there are some challenges to accomplishing that.&rdquo;</p>
<p>Biofuels</p>
<p>Todd Neeley reported yesterday at DTN (link requires subscription) that, &ldquo;U.S. biodiesel production is at a virtual standstill, and industry officials are spending their days shouting from the mountain tops to anyone who will listen.</p>
<p>&ldquo;&lsquo;We&rsquo;re getting close to the point that it&rsquo;s just time to shut the whole thing down,&rsquo; said Bernie Crowley, general manager and owner of Delta American Fuel based in West Helena, Ark.</p>
<p>&ldquo;Since the $1 biodiesel blenders tax credit expired at the end of 2009, the industry has been in shutdown mode and jobs have been lost.&rdquo;</p>
<p>The article added that, &ldquo;During a National Biodiesel Board press conference Thursday, industry representatives repeated what has become a desperate battle cry &mdash; renew the tax credit that makes biodiesel competitive with fossil-based diesel.&rdquo;</p>
<p>Mr. Neeley explained that, &ldquo;Even if the tax credit is extended for one year, according to industry representatives, it would only be enough to effectively jumpstart production before the credit expired again.</p>
<p>&ldquo;That&rsquo;s because it would take significant time to rehire employees and return to full production levels.</p>
<p>&ldquo;That&rsquo;s why the industry needs a three- to five-year extension of the credit to provide at least some certainty for creditors, [Jeff Stroburg, chairman and chief executive officer of Ames, Iowa-based Renewable Energy Group, one of the largest biodiesel producers in the country] said.&rdquo;</p>
<p>Climate Issues: American Power Act</p>
<p>Amy Harder reported yesterday at the National Journal Online that, &ldquo;Industry and environmental leaders alike say bipartisan support for the climate and energy bill is essential for its passage.</p>
<p>&ldquo;Yet following Sen. Lindsey Graham&rsquo;s withdrawal from the negotiations last month, no other Republican has signed on to the bill and none have yet signaled an openness to doing so. That has not gone unnoticed by moderate lawmakers whose support will be essential in moving the bill, unveiled Wednesday by Sens. John Kerry, D-Mass., and Joe Lieberman, I/D-Conn.</p>
<p>&ldquo;&lsquo;Senator Graham&rsquo;s absence makes the bill&hellip; a steeper climb,&rsquo; Finance Chairman Max Baucus, D-Mont., said Wednesday. &lsquo;A factor, frankly, is the degree at which the proposal has legs, and that is yet to be determined,&rsquo; said Baucus, deflecting questions as to when or whether he&rsquo;d bring the bill in front of his panel.&rdquo;</p>
<p>Ken Anderson reported yesterday at Brownfield that, &ldquo;[Sen. Mike Johanns (R-Neb.)] says the Kerry-Lieberman bill would lead to higher costs for farmers and ranchers and would, in his words, &lsquo;be destructive for agriculture.&rsquo;&rdquo; The Brownfield link included extended audio remarks on this issue from Sen. Johanns.</p>
<p>Dan Looker reported yesterday at Agriculture Online that, &ldquo;A day after two senators from the Northeast, John Kerry and Joe Lieberman, introduced the American Power Act, their version of a bill to slow global warming was blasted by their Midwestern colleague, Senator Tom Harkin (D-IA).</p>
<p>&ldquo;&lsquo;It just seems to me there&rsquo;s too much emphasis in this bill on going down the nuclear and fossil fuel route,&rsquo; Harkin told Agriculture.com in a press conference Thursday.&rdquo;</p>
<p>Mr. Looker added that, &ldquo;Harkin said he&rsquo;d like to see the bill put more emphasis on building a national electrical power grid, something wind energy advocates favor. And he said it doesn&rsquo;t provide enough support for increasing energy conservation, which Harkin described as the least expensive way to reduce greenhouse gas output.</p>
<p>&ldquo;&lsquo;In terms of agriculture, we have to make sure there&rsquo;s a good role here for renewable fuels,&rsquo; Harkin said, mentioning ethanol, biodiesel and fuel from algae.&rdquo;</p>
<p>A news release from Wednesday by American Farmland Trust noted that, &ldquo;In a statement today, Jon Scholl, President of American Farmland Trust (AFT) said:</p>
<p>&ldquo;&lsquo;We are pleased to see that Senators Kerry (D-MA) and Lieberman (I-CT) have gone forward and introduced their American Power Act legislation. While our initial analysis is not yet complete, the text indicates that they have incorporated many, if not all of the items brought forward previously by Senators Stabenow (D-MI) and Baucus (D-MT) in the Clean Energy Partnerships Act of 2009, to address the concerns of farmers and ranchers.&rsquo;&rdquo;</p>
<p>For more on the Clean Energy Partnership Act, click here (overview) and here (text).</p>
<p>And Russell Berman reported yesterday at The Hill&rsquo;s Energy Blog that, &ldquo;House Speaker Nancy Pelosi said Thursday she would have no problem subjecting her members to another tough vote on climate change legislation before the November election if a far-reaching bill passes the Senate.</p>
<p>&ldquo;&lsquo;They&rsquo;ve already gone down that path,&rsquo; Pelosi (D-Calif.) said of House Democrats at her weekly press conference, referring to the chamber&rsquo;s passage of climate change and energy legislation last June.&rdquo;</p>
<p>Climate Issues: EPA &ldquo;Tailoring Rule&rdquo;</p>
<p>Reuters writers Timothy Gardner and Ayesha Rascoe reported yesterday that, &ldquo;The Obama Administration finalized greenhouse gas rules for big factories and power plants on Thursday, giving momentum to the troubled climate bill in the Senate.</p>
<p>&ldquo;Starting next year, the Environmental Protection Agency rules would require large power utilities, manufacturers and oil refiners to get permits to operate or prove they are using the latest green technology to cut emissions when building new capacity.</p>
<p>&ldquo;President Barack Obama has pushed the EPA to roll out emissions rules and polluters could face more stringent future climate regulations if the climate bill fail.&rdquo;</p>
<p>The Reuters article pointed out that, &ldquo;The rules would subject power plants, factories and oil refineries that emit 75,000 tonnes of carbon dioxide equivalent and already under clean air regulations to get operating permits beginning in January 2011. Regulated polluters would include big coal-fired power plants and heavy energy users such as cement, glass and steel makers.</p>
<p>&ldquo;Waste landfills and factories not already covered by clean air laws that emit at least 100,000 tonnes of greenhouse gases a year would get a six-month extension and would not be regulated until July 2011.</p>
<p>&ldquo;Sources that pollute less than 50,000 tonnes per year would not be regulated until 2016, if ever, said EPA air official Gina McCarthy.&rdquo;</p>
<p>Bloomberg writer Jim Efstathiou Jr. reported yesterday that, &ldquo;The rules presented today are designed to deflect criticism that small businesses would be forced to comply with emissions limits, EPA assistant administrator Gina McCarthy said on a conference call with reporters. Under the Clean Air Act, sources that emit 250 tons annually are subject to restrictions.</p>
<p>&ldquo;Starting next year, the EPA will regulate greenhouse gases from new power plants, oil refineries and factories that emit more than 100,000 tons per year, and from existing plants that increase emissions by more than 75,000 tons per year.</p>
<p>&ldquo;&lsquo;The EPA is trying to be careful to limit these requirements to the biggest sources of greenhouse gases,&rsquo; said Frank O&rsquo;Donnell, president of the Washington-based environment group Clean Air Watch.</p>
<p>&ldquo;Next year, the EPA will begin consideration of a rule to extend the restrictions to smaller emitters. If the limits are expanded, they won&rsquo;t cover businesses that emit less than 50,000 tons per year, McCarthy said.&rdquo;</p>
<p>The article noted that, &ldquo;&lsquo;EPA&rsquo;s legal basis for the rule rings hollow,&rsquo; Senator James Inhofe, an Oklahoma Republican who once called manmade global warming a hoax, said today in a statement. &lsquo;Even if the courts uphold the rule, EPA makes absolutely clear that commercial buildings eventually will find themselves caught in the web of EPA&rsquo;s global warming regime.&rsquo;&rdquo;</p>
<p>Amy Harder reported yesterday at the National Journal Online that, &ldquo;The EPA finalized its &lsquo;tailoring rule&rsquo; for greenhouse gases today, limiting regulation to large stationary emitters like power plants and oil refineries. But Sen. Lisa Murkowski, R-Alaska, who has spearheaded efforts to strip the agency of its regulatory power, remains unsatisfied.</p>
<p>&ldquo;&lsquo;It&rsquo;s the question of whether you regulate me now or regulate me later,&rsquo; Murkowski spokesman Robert Dillon said. The senator will continue to seek a vote on her disapproval resolution &mdash; essentially a congressional veto of EPA greenhouse gas regulations &mdash; by the June 7 deadline. The resolution has 41 co-sponsors, including Democrats Mary Landrieu of Louisiana, Ben Nelson of Nebraska, and Blanche Lincoln of Arkansas. The resolution needs 51 votes to pass, but it very likely won&rsquo;t get the needed approval from President Obama.&rdquo;</p>
<p>Rep. Earl Pomeroy (D-ND) indicated in press release from yesterday that, &ldquo;As the Administration took another step forward today toward regulation of greenhouse gas emission, Congressman Earl Pomeroy blasted the move and warned that the effort threatens to stall investment in jobs for the domestic energy industry in North Dakota and across the nation.</p>
<p>&ldquo;Pomeroy said he would keep pushing his legislation that would strip the U.S. Environmental Protection Agency (EPA) of its authority to regulate greenhouse gases. He is also pushing to remove $56 million from the president&rsquo;s budget request that would be used by the EPA to regulate greenhouse gases. Pomeroy&rsquo;s comments came as the EPA announced final rules to regulate power plants, oil refineries and other similar facilities.&rdquo;</p>
<p>A news release issued yesterday by USDA noted in part that, &ldquo;Agriculture Secretary Tom Vilsack today issued the following statement on the Environmental Protection Agency&rsquo;s Greenhouse Gas Tailoring Rule:</p>
<p>&ldquo;&lsquo;I want to thank the Administrator for agreeing to seek further comment on how to address the greenhouse gas benefits of bioenergy under the Clean Air Act. Energy derived from woody biomass, switch-grass and other sources has potentially enormous benefits for reducing greenhouse gas emissions, developing clean, home-grown energy, and providing economic opportunities for rural America. Markets for woody biomass can also bolster forest restoration activities on both public and private lands that improve the ecological health of our forests.&rsquo;&rdquo;</p>
<p>***</p>
<p>A news release issued yesterday by UC Davis (&ldquo;Rising CO2 levels threaten crops and food quality&rdquo;) noted that, &ldquo;Rising levels of atmospheric carbon dioxide interfere with plants&rsquo; ability to convert nitrate into protein and could threaten food quality, according to a new study by researchers at the University of California, Davis. The scientists suggest that, as global climate change intensifies, it will be critical for farmers to carefully manage nitrogen fertilization in order to prevent losses in crop productivity and quality.</p>
<p>&ldquo;The study, which examined the impact of increased carbon dioxide levels on wheat and the mustard plant Arabidopsis, will be published in the May 14 issue of the journal Science.&rdquo;</p>
<p>Copyright&copy;  FarmPolicy.com. All rights reserved. <a href="http://www.farmpolicy.com/?p=2355" target="_blank">Original Article</a></p>
