

<p class="newsheader_t1">Idaho Wheat</p>
<p class="newssubhead_t1">Sanow's Market Sense </p>
<p>John Sanow DTN Analyst</p>
<p>Could the situation grow any worse in U.S. wheat country? Drought conditions in the southwest Plains and excessive rains/flooding in soft red winter areas took the DTN Winter Wheat Crop Condition Index to its lowest level on record at 24 points, surpassing the previous low set in June 2002 at 26 index points. Or the slow planting pace in the Northern Plains -- as of Sunday, May 22, only 54% of the crop was in the ground, 35 percentage points below the average pace. The long-range weather forecast holds little hope that conditions will improve in either area.</p>
<p>No secret here -- the domestic wheat crop is in dire straits. Growers in the Canadian Prairies are struggling with a situation similar to their spring-wheat-growing counterparts in the U.S. Western Europe is suffering through a historic drought of its own, threatening the winter crop in France and Germany, the No. 1 and No. 2 producers out of the EU. This sets the stage for significantly reduced yields if rains don't come soon. In fact, it may be too late on sandier soils according to reports out this week.</p>
<p>With all these bullish headlines, one would think the commercial outlook would be growing more bullish. In the Minneapolis market it is. The nearby July-to-September spread is inverted while the new-crop September-to-December holds a small carry, with both indicating a bullish supply and demand situation. Throw in for good measure the firming national average basis that is approaching 90 cents over the July contract and it's easy to build a bullish argument for the high-protein wheat class.</p>
<p>However, the picture is much different in Kansas City and Chicago. The carry in futures spreads remains strong. The nearby Chicago spread is over 300% of full commercial carry while Kansas City is about 140%. Part of the reason in Chicago is the failed variable storage rate program that has rewarded commercials for storing SRW wheat. Is this the real issue though? Keep in mind, a neutral commercial outlook is between 66% and 33% of full commercial carry. That's an awfully wide gap to fill.</p>
<p>The rallies in Kansas City and Chicago recently have been tied largely to a fresh inflow of noncommercial money; they were not fundamentally driven. Sure, the wires have been littered with bullish headlines. There are cracks starting to form though, supporting what the spreads have been telling us.</p>
<p>As we all know, wheat is grown in almost every nook and cranny across the globe. At one time, China's largest wheat-producing province, Henan, was expected to see yields decline by 10% from the previous year. After timely rains, projections are currently on par or slightly better than 2010 when about 115 million metric tons were produced. Early harvest results in southern areas are better than expected and seem to support this argument. The world's second-largest producer, India, appears poised to harvest an all-time record crop by as much as 2 mmt, bringing total production to over 86 mmt, opening the door to resume export business.</p>
<p>Russia, the Ukraine and the rest of the Black Sea Region are on track to produce much larger crops than a year ago. This led Ukraine to lift its export quota program Wednesday, while rumor has it Russia will halt its export ban sooner rather than later.</p>
<p>Estimates from Iraq project a 2 mmt to 2.5 mmt jump over the prior year, meaning they will rely less on imports. Australia will plant 3.24 million hectares, 14% above the 2010-2011 marketing year. Setting up the largest crop they've seen in at least 12 years if weather cooperates. And these were reports for just this week.</p>
<p>The myriad of production issues will certainly cut into domestic ending stocks for the 2011-2012 marketing year. However, the expected decline in yields and acreage could partially be offset by a sizeable decrease in export activity. USDA projects exports to decline by 225 mb to 1.05 bb in 2011-2012. But it's plausible to see a larger drop that could approach the 2009-2010 exports of only 881 mb when other exporting countries come back online.</p>
<p>On the world side of the ledger, talk of the stocks situation growing tighter may have been a bit premature; instead it may increase. The May WASDE report projected ending stocks-to-use at 27%, in and of itself still a comfortable level historically as compared to the five-year average of 25% and the 10-year average of 26%.</p>
<p>What does all this mean for prices? If the HRW (Kansas City) and SRW (Chicago) markets are to continue rallying, buying will need to come from the noncommercial side. And if that interest subsides, there will be little help from the commercial side to break the fall. In HRS (Minneapolis), it's a polar-opposite situation as the commercial outlook grows more bullish longer-term. This should mean prices should rally with more authority when investment money actively flows in, with breaks to the downside less pronounced due to solid commercial support.</p>
<p>Only time will tell what actual yields will amount to in every stretch of the world. For now, commercial traders are more than comfortable with the future availability of winter wheat supplies, not so much in spring wheat. It's a big world after all.</p>
<p>Copyright&copy; Idaho Wheat. All rights reserved. <a href="http://www.idahowheat.org/news/default.asp?id=4656" target="_blank">Original Article</a></p>
