

<p class="newsheader_t1">Farmandranchguide.com</p>
<p class="newssubhead_t1">Closing Grains Commentary</p>
<p>DTN Closing Grain Comments - By Darin Newsom, DTN Senior Analyst: Grain contracts closed at or near session highs following a late surge. Soybeans led the way, with the wheat complex right on its heels. Corn was lethargic throughout the session before its bullish close.<br />
  September Wheat finished up 9 1/2 at 678 1/2, 5 1/4 off the high and 20 up from the low. December Wheat closed up 8 1/4 at 701 3/4. This was 18 1/4 up from the low and 4 3/4 off the high. Chicago wheat traded 12-14 cents higher late in the session today on short covering and a decent recovery in the other grains. This was prompted by the idea that the USDA will decrease the world production estimates next month. Eastern Spring Wheat areas of Ukraine could trend warmer and drier to finish out the month and could possibly continue into July. The 6-10 day precipitation forecast calls for.25-1.5 inches of rain for the FSU winter and spring wheat crops. European wheat futures saw late gains and reached a new 3 week high after U.S. wheat futures began to rally. Paris Wheat saw follow through buying after it was announced that France likely sold Algeria 600,000 tonnes of milling wheat. Iraq has issued a tender to buy at least 50,000 tonnes of all origin wheat and exports sales are estimated at near 400,000 tonnes in tomorrow morning's export sales report. Chicago July wheat rallied into the close today, despite a firmer U.S. Dollar. September Oats closed down 4 at 302 3/4. This was 1/2 up from the low and 7 1/2 off the high.</p>
<p>August Soybeans finished up 15 3/4 at 1437, equal to the high and 22 up from the low. November Soybeans closed up 11 at 1395 1/2. This was 25 up from the low and 1/4 off the high. August Soymeal closed up 1.6 at 424.3. This was 6.8 up from the low and 1.0 off the high. August Soybean Oil finished up 0.31 at 50.94, 0.33 off the high and 0.65 up from the low. Soybeans rallied for the fourth consecutive session today on a warm and dry forecast for the next 10 days. Soybeans traded 9-11 cents higher heading into the closing bell. Scattered showers are expected to move from eastern Nebraska to the northern plains in the short term forecast. The 11-15 day map continues to show dry conditions for the eastern Midwest and parts of the Delta but some models do not show heat. Overall, no drastic change has been made to the forecast for the next 2 weeks. December soybean oil rallied today and made new highs near 52.00 on rumors that China bought Argentinean soybean oil and could soon shift their demand to the US soybean market due to available supplies. The U.S. Dollar traded lower for most of the session, but rallied late in the afternoon as the Fed released statements on the status of the U.S. economy. Soybeans were able to shrug off the lower commodity trade, led by crude oil, and finish near the highs of the session. Exports sales are estimated at near 850,000 tonnes for tomorrow mornings export sales report.<br />
  September Corn finished up 1 1/4 at 568 3/4, 1 off the high and 16 1/4 up from the low. December Corn closed up 3 at 566 1/2. This was 17 3/4 up from the low and 1 off the high. December corn traded a 19 cent range today and finished positive near the end of trading today. The 11-15 day forecast is unchanged with cooler temperatures for most of the Corn Belt but extremely light rainfall. December corn saw profit taking after yesterday's rally but found support on an uninspiring weather forecast to finish out the month of June and heading into July. Southern Midwest and northern Delta regions should begin pollination next week and the prospect for higher than normal temperatures and below normal rainfall will likely reduce yield. Traders see weekly export sales for corn near 550,000 tonnes for the release for tomorrow morning. December corn settled near the highs of the day despite a firmer U.S. Dollar following statements made by the Fed this afternoon. September Rice finished down 0.005 at 14.745, 0.105 off the high and equal to the low.</p>
<p id="p2">Copyright&copy; Farmandranchguide.com. All rights reserved. <a href="http://www.farmandranchguide.com/marketwatch/grains/closing-grains-commentary/article_e464667c-bb21-11e1-ada4-001a4bcf887a.html" target="_blank">Original Article</a></p>
