

<p class="newsheader_t1">IPTV.org</p>
<p class="newssubhead_t1">Market Analysis: Darin Newsom and Don Roose</p>
<p>Borg: Here now to lend us their insight on these and other trends are two of our regular market analysts, Darin Newsom and Don Roose. Gentlemen, welcome back. </p>
<p>Roose: Thank you. </p>
<p>Newsom: Thank you. </p>
<p>Borg: Well, you know, we hear this week from drought experts and the U.S. Government Drought Forecasting Center that we are in danger of more dry weather, and it's not looking any better, although there was some rain across portions of the Midwest this past week. But that doesn't seem to be reflected in the corn and soybean markets. </p>
<p>Roose: Well, you are right, Dean. The market is not very respectful. The weather problems that we've had so far, you have to ask yourself why. Probably part of the reason is we want to move to lower levels. Our crop ratings are severely under a year ago but the market continues to move lower. And it's all about weather this time of year. If we miss the moisture that we forecast on Friday, you know, Monday is going to be a very explosive day. </p>
<p>Borg: Darin what do you think the markets are going to be factoring in the weather. </p>
<p>Newsom: I think that we are just not quite there yet, where we have moved into a full-blown weather market. We are still dealing with this overall bearish view of commodities. You mention the Goldman Sachs Index was down again today. Gold did turn around. We started to see cotton turn around, so hit and miss. We are starting to see some commodities begin to react. But the market --the sector in general seems to be struggling and until we change that, and till we actually get into this full-blown weather market, I don't think we're going to register. </p>
<p>Borg: And the weather market, what more does it need? </p>
<p>Newsom: I think we need to - number one we're going to have to get investors interested. To do that we're going to have to actually start to see talk of real damage being done to production numbers. We had a USDA report out last Tuesday, I believe. New crop corn wasn't changed at all. Overall yield was left the same, overall production, in fact all the corn numbers were left unchanged. So investors had no reason to become interested in this market, no reason to be concerned, so they stay on the bearish side. </p>
<p>Borg: Don, we've been talking corn and soybeans here, but let's include wheat now. Wheat, is that also affected because parts of the wheat growing area are dry too. But a note here from Janet in Kansas talking this past week says they are done harvesting wheat and it's the earliest ever. </p>
<p>Roose: I think that the wheat is coming off very quickly. Down South, you know, the yield overall, it was a little bit disappointing from the lofty levels that we expected. We are moving north on wheat harvest, and we've got some timely rains in some of the wheat areas there. But around the world, we still have abundant supplies of wheat. So we do have a buffer for a little bit of a yield loss, which is exactly what is happening. </p>
<p>Borg: Cotton, though, is not reflected the air and bucking the trend. </p>
<p>Newsom: Cotton market in general remains neutral to bearish if you want to look at the supply and demand situation. There's really nothing to light a fire under this market, but it's been beaten down so far. We've seen some very high prices coming off of 2008. In 2010 we made another run, but the market has just been blasted here over the last six months. What we're starting to see is a little bit of money coming back into this market possibly on the idea that it's overvalued and undersold and all these technical terms that investor traders will look at. This is what is starting to provide a little bit of support to cotton. Maybe it can get rolling a little bit. </p>
<p>Borg: And yet this week, even with a decline in the corn market, we saw farmers selling corn. They're always selling corn, but really a lot of corn moving this week. </p>
<p>Roose: I think we're going to find a big report coming up June 29. The stocks in all positions and the acres. I think a producer hit a time frame where he is starting to move stocks aggressively. But Dean, when you look at the acres, I think there's a chance that the acres could be 500,000-1,000,000 more on this report that's coming up June 29. And the soybean acres can be up a 2-3 million. So that's giving us part of this buffer when we are talking about why isn't the grain market bouncing and the weather issues. </p>
<p>Borg: Then I might say why isn't also it being reflected in the livestock markets? </p>
<p>Roose: And that's a good question because part of the issue with the livestock market is if the grain market moves lower, the livestock will also move lower in sympathy but the crush and that's exactly what has happened. That's part of the reason wth this lofty grain values is why the livestock market is so lofty. This week we had a big setback on cash cattle with supplies growing and weights growing. </p>
<p>Borg: In hog and cattle markets, what do you see there? </p>
<p>Newsom: The hog market is actually - Don mentioned -- the pressure that we've seen in the cash cattle market, opposite story completely in the cash hogs. We've actually got a short supply situation. We've got packers really pushing this market. We have very strong cash markets. It looks like we want to stick with this for a little while. We turn the trend of the cash market up; I think it's going to continue to pull the futures market as well. So where the cattle industry looks bearish, at least for short term, it looks like it's going to be quite bullish for hogs. </p>
<p>Borg: And feeder cattle. </p>
<p>Newsom: Feeder cattle could continue to struggle. The overall break even prices in the cattle market, I think it's going to help bring some of these feeder cattle prices down as well. </p>
<p>Borg: Is that the way you feel too, Don? </p>
<p>Roose: Yes, I think when you look at the hog market, just a little bit different. We think that the 2013 supply side is going to be quite bearish. So we think this is very much a short-lived situation that we think that there has to be some risk management that should be implemented. </p>
<p>Borg: Are these at all being driven in the commodity markets? Are they being driven by --we said earlier in the program with the election coming up in Greece and China's economy and so on. What do you think Don? </p>
<p>Roose: Most definitely. I think that the dominant issue is weather, but I think right behind that is what's happened in the world economy. We just have huge debt loads around the world, and we just can't seem to come to grips with them, so the election Sunday night in Greece are going to be a big deal on how stable the markets are on the outside. </p>
<p>Borg: How would that affect --I mean if there's a certain outcome there, what are you looking for? </p>
<p>Roose: If it's a poor outlook, what I think is its risk of type of trade where -- And if we have some decent moisture at the same time, that's probably going to cause a lot of selling in the marketplace. But right now the odds favor that they're going to have a positive election, Dean. </p>
<p>Borg: And China? </p>
<p>Newsom: China is the big question because that's the number one demand market that there is. And right now, even though there has been talk of slower growth in China, there's still growth. No one really knows for sure when and if they're ever going to step out of these markets. There's still a very active buyer in new-crop soybeans and wheat and other markets. So these headlines seem to come and go through the market very quickly about Chinese problems, but if we ever were to see a large-scale setback economically or a large slowdown in China, I think at first it would be reflected in these immediate markets at the energy complex and the soy complex overall oil seed markets globally and then spread over to the other commodities as well. </p>
<p>Borg: Let me ask what are advising people who call you now and ask about specific commodities. What are you advising them on corn? </p>
<p>Newsom: In the corn market as Don pointed out we're going to have to be pretty careful with this market because there are still so many question marks. I think that long-term, it's going to be real difficult to establish any sort of long-term rally unless we see a full-fledged weather market. So sell the rallies and make sure you lock in good prices. New-crop basis is still quite strong. I think you're going to want to look at trying to get some sales on soybeans. So I think you can sit back a little bit and the market is indicating with its forward term that we've still got a very bullish situation ahead of us. </p>
<p>Borg: Don, would you echo that on soybeans, for example. </p>
<p>Roose: Next week is a negative timeframe seasonally, where this next week we usually come under a lot of pressure, so the soybeans have the best fundamentals. But we may have seen the most bullish report already out of soybeans. Remember the next report you're going to have bigger acres. So the soybeans are going to find support around 16, $13 on November beans and then quickly at 1250. But we think 1250-12 should be a big support, but it's going to take a lot of weather problems, we think to push us back up to the double top of $14 on November beans. </p>
<p>Borg: Would you advise people who are looking to add feeders to feedlots right now to be very careful because of the drought? It may drive corn prices higher? </p>
<p>Roose: I think risk management is always key. But right now actually we think that the odds favor that we have normal patterns start to develop and that the grain market comes under some pressure. We think it's not out of line to go to 4-450 on December corn, and so we would be careful with extending big coverage. </p>
<p>Borg: You said the odds favor that we're going to get rain? </p>
<p>Roose: The odds favor, from our standpoint, we're moving into that time of year. It seems odd that we're moving into closer to an El Niño than a La Nina. So it does. </p>
<p>Borg: It looks like you're the eternal optimist. A lot of farmers like to hear that. What were you advising on hogs and cattle? </p>
<p>Newsom: I think, you know, with this rally that we're seeing in the hog market, you might want to get some locked in. As Don said, 2013 certainly does look like it's a much more bearsish situation. Cattle market, you're going to have to try to find the numbers that work out for the type of selling that we saw this week. If you get any type of life in these markets at all, you can lock in some profits, so do it. I would treat it very cautiously but right now it seems like the hogs have the best chance of posting a run. </p>
<p>Borg: Don, are you advising people now with the corn prices the way they are, soybean prices, to lock in future feed needs? </p>
<p>Roose: Well, we were. I think you can in a selected manner. I would use the proper risk management tools because if we are right and we do go into a more normal weather pattern, the odds favor with a big cushion that we continue to try and move lower rather than higher. But it's all up to weather, Dean. </p>
<p>Borg: And on weather, if there is rain across the Midwest, at least a bit of it this week, in fact on the weekend, is that at all enough to move markets? </p>
<p>Newsom: It very well could be. Because number one it keeps the bears happy and it doesn't give the bulls anything tostart to build on. What we're saying is next week western half of the Corn Belt, western half of the Midwest will stay --has a good chance of rain. Eastern half can stay relatively dry. It could be a battle forming there, but you're really going to have to build something solid for these bulls to get interested, or they're going to stay on the sidelines. </p>
<p>Borg: Thanks so much, Darin Newsom and Don Roose. That wraps up this edition of &quot;Market to Market.&quot; But if you'd like more information from Darin and Don on where these volatile markets just may be headed, visit the market plus page at our website. You'll find expanded market analysis, audio podcasts, streaming video of our program and links to our Twitter feed and Facebook page, all free at the &quot;Market to Market&quot; website. Many of you posted comments on those sites last week, expressing your condolences over the passing of our colleague Mark Pearson. We thank you for your support and want you to know that &quot;Market to Market&quot; will name a new host in the weeks ahead. And just as longtime viewers remember that Mark Pearson originally was known simply as Chet Randolph's successor, our next host of &quot;Market to Market&quot; will always be known as Mark's. And until next week, thanks for watching. I'm Dean Borg. And as Mark would say, have a good week.</p>
<p id="p2">Copyright&copy; IPTV.org. All rights reserved. <a href="http://www.iptv.org/mtom/story.cfm/marketanalysis/9614/mtom_20120615_3742_marketanalysis" target="_blank">Original Article</a></p>
