

<p class="newsheader_t1">Iowa Public Television</p>
<p class="newssubhead_t1">Market Analysis: Darin Newsom</p>
<p>Pearson: Here now to lend us his insight on these and other trends is one of our regular market analysts, Darin Newsom. Welcome back.</p>
<p>Newsom: Good to be here, Mike.</p>
<p>Pearson: We're glad to have you. I'd like to talk a little bit, we mentioned the fouryear high, the fouryear high and the S&amp;P 500. What effect is that having on commodity markets, or is it having an effect?</p>
<p>Newsom: A lot of times what we see is how all these markets are connected. If the Dow and some of the stocks are starting to slowly climb up, it's creating money. Many times that money starts to work its way over into the commodities and whatever happens to be the hot sector at that point.</p>
<p>Pearson: This year we can sit back and we've got the Dow going to highs in grains pushing to new highs. Are they working together?</p>
<p>Newsome: It looks like it at face value, but there's so many other things that are going on right now. The connection between some of these markets have actually been weakened. Even though it looks quite strong, it's actually been weakened. The grains are off on their own. They are certainly trading their own fundamentals. They're trading their own market influences. It just so happens to coincide with this, as you put it, into this slow creep that we've got going into the Dow and S&amp;P. It makes it look nice. Right now basically people are looking to where they can put the money, but volume is still relatively low.</p>
<p>Pearson: So really not a lot of connection.</p>
<p>Newsom: There's not at this point. Not like we've seen in the past, that's for sure.</p>
<p>Pearson: All right. Let's move into the commodities a little bit and talk about wheat. What do are you seeing with wheat? What should producers be working with here?</p>
<p>Newsom: The biggest thing that we've got going in wheat, we have spring wheat harvests that is progressing nicely. We've got some yields that are actually coming in better than expected, but the biggest thing in wheat is when is the next headline going to hit coming out of Europe, coming out of Russia, in particular. There's a lot of talk this week. We saw it late in the week the way the wheat market reacted that at some point, probably within the next 6090 days, Russia and Ukraine could run short of exportable wheat. Week they've been doing a lot of business here lately. They haven't been trading the outside world hasn't been turning to the U.S. yet. They feel like the U.S. stocks are overpriced. But Russia doesn't have a lot of stocks left. Ukraine doesn't have a lot of stocks left. We go to Europe and they've had their own weather problems, and they're not going to be able to fill the void. At some point this is going to come back to the U.S. and we're going to see some folks knocking at the door and we're going to start to see U.S. export business picking up. I think it's inevitable once we get into the late 2012, early 2013, I think the U.S. could become the dominant player in the global wheat exports.</p>
<p>Pearson: So as producers are looking at the 6090 days out, what should they be looking at? What kind of prices do you think we could see in wheat?</p>
<p>Newsom: Right now I think we're going to want to sit back for a little bit because we have seen some pressure in the winter wheat markets. Of course, we've got the spring wheat moving lower. The problem is as we get closer, in that $9, $10 range, there's just not a lot of outside buying interest coming into this market. We saw some noncommercial selling this week as of Tuesday, according to the latest CFTC Report. So wheat is one of those markets that's going to take something spectacular. It's going to take that headline saying there is now an export ban in Russia to really push this market higher. Are these attractive levels? I need to step in and start getting some contracting done. If you've got old crop, be sure it's just harvested. Keep filling this market and keep selling into this market. You don't want to hold a lot waiting for something to happen, but as we get closer, as we get, again, deeper into the year, I think it's going to give us some opportunities in this new crop. A lot will depend on what we think we are going to grow. It's still very dry in the Southern Plains. When we start drilling in that area, it's going to be difficult to get a good stand here before it goes into dormancy. There's a lot of issues yet to play, but do feed this market a bit and be very careful about, you know, the problem that wheat has just not being able to push a great deal higher because of the high prices. So take advantage of where the market is at and keep your eye on the future.</p>
<p>Newsom: Absolutely because I think we are going to see better opportunities down the road.</p>
<p>Pearson: All right. Let's talk corn a little bit. We've been in weather market corn and now we've pretty much seen what the drought has to offer. Well, producers or other, where do you think corn prices could go?</p>
<p>Newsom: Corn is going to be very interesting. I'm hearing more and more about not just with wheat. Nine and tendollar corn is going to have to happen because these production numbers keep coming down. We get a lot of emails coming in, reports coming in from all over the Midwest saying  telling us what they're seeing so far in yields. Many of them are sub 100 right now. Where do we take over the yields from here? I can't help but feel that we're going to keep ratcheting it down, maybe not as much as we've seen since the USDA reports, but certainly we could see these numbers ratchet down. Overall production continuing to come down. So I think there's going to be this base of support underneath the market on tight supplies, but the problem corn is going to have in pushing significantly higher is demand is going to come down as well. It's one of those markets that we can continue to whittle away demand. We've already seen it happen in the feed. We've seen export business slow down, not only because of our price, not only because of our lack of supplies, but the river problems are also hurting our movement to ports. So demand in demand for corn could continue to come down. So I think that's going to limit the possibility of gains, but if we look on out to the new crop, I would not get too excited about making 2013 sales right now, because we're going to see a fight next year over some dry acres and both corn and beans are going to be high prices and they're going to be fighting for those acres. We are going to still see potential for not only this year's crop, but next year's crop, so putting some higher numbers on the board.</p>
<p>Pearson: All right. With that in mind, what should producers who are looking at the yields they're expecting in the fields, is there a price they should consider selling?</p>
<p>Newsom: You know, we're up above $8 now on the December corn contract. We're right near $8 and that's an attractive price. The problem is going to be how much do you sell. If you say I want to do 50 percent of what I was expecting or 50 percent of what I'm expecting now, you have to be very careful because that 50 percent could turn in to be 75, 80, maybe 100 percent, if not more. So you have to be very careful. You have to put you could throw some put options on there and the volatilities set those kinds of expenses. Just to to give yourself some price protection because you don't really know what you might have out in the field. It was also give you the opportunity to take advantage of a market if it really starts to get its second wind and move beyond that $9, possibly making a run at 10. Not out of the question, by any means.</p>
<p>Pearson: All right. Is that sort of the same advice you would be giving to soybean producers out there?</p>
<p>Newsom: Soybean producers are little bit different. Again, we are sitting at very intricate levels. We're up in that $15, $16 range. The problem that soybeans have is that, you know, we talked about corn demand being whittled back. That really can't happen in soybeans. It has a more inelastic demand in that China is going to want its beans  it's going to want it's bean meal. We're going to have to continue to see exports moving to China, business coming from China. The problem is we have South America with a short crop. They don't have a lot of supplies to fill the gap that we're not going to be able to hit this year. So I would sit back on beans. It is a dangerous market. It's got a structure where it's very highpriced, the volatility is up. And investment traders already hold a large position, so they're going be willing to buy. That's not a combination for higher prices. So if we dip back and say  back down in the 14. 50, $15 range, I think we're going to see a lot of buying coming in at that point. The key to all these markets is to watch the future spreads. Right now we've got $1. 90 premium November 2012 over the July 2013 contract. That tells me  that inverse tells me that there's a lot of concern about there not only about supplies but about meeting demand as well.</p>
<p>Pearson: All right. What should producers be looking up for price point for this year's crop?</p>
<p>Newsom: This year's crop, anything over that 15 $15, $16 range is going to look good. Again, as with corn, we're talking about a situation where it's going to be difficult to pinpoint exactly what we're going to have. There's so much talk here recently about the cooler weather, and rain has maybe helped this soybean crop more than what it would've helped the corn. I have my doubts. We've seen this before. I'm not sure we actually salvage the soybean crop as much as what many people feel. So I don't think we can push this 2012 crop higher. The way the market is set up right now, I don't want to get too far ahead of it. I'm going to let it continue to run. There's a lot of talk about $20 beans out there over the course of the 2012, '13 marketing year. Is it impossible? We just had a situation globally, which is what it could be, $20 may not be that hard to hit.</p>
<p>Pearson: Let's move over to livestock. We had a rise in feeder cattle prices this week. Where do you see that going?</p>
<p>Newsom: Feeders have really struggled lately. They had a nice week this week, and so much of that has been off what corn is doing, and they will slow down demand for feeders. It looks like that matter is stabilized. We've seen a stronger cash in the rise. That's helping more but we're seeing buying coming into the live cattle market. It's going to help the feeder cattle market as well. The big problem is that at some point, the issue of reduction of the herd size. We're doing away with some of the herd side already. That is hurting. As we talked about, that is hurting feeder demand, so I don't think that's going to go away soon. We're going to see these little pops in the market, but if corn takes off and runs again, I think it's going to be very hard to maintain buying interest in feeders.</p>
<p>Pearson: And what do you see that having an effect on, fat cattle?</p>
<p>Newsom: The fat cattle market going forward really looks like it has found some support. We weren't able to take out some old highs here this week, but the market still looks well supported by the cash side. So at least over the next month to three months, maybe over the next quarter, we should see support in the market as a whole. At that point, it could start to drop off. But by and large, I think we're going to see some support in this cash market. I think live cattle should be able to hold firm for now.</p>
<p>Pearson: Looking at the longer term picture, with a reduction in herd size, do you see fat cattle rising over next summer?</p>
<p>Newsom: If we see the type of herd reduction that's being talked about, and we're already hearing about pretty good we've been hearing about good cow kill at this point this early in the season. That is going to start to bring and come back into play, say, as we get into the first quarter of 2013. I think in the first quarter on, then I think we start to see this market firm because we're just not going to have as many head moving through the system at that point. I think it's a real risk in the market. I think that we could sit back and say it's kind of setting up, that we're going to be looking at a much more bullish pricewise market, but the promise of going to be bottom line. The margin is still a pretty negative in the livestock industry as a whole, particularly in the live cattle.</p>
<p>Pearson: All right. Let's move over to hogs a little bit and talk about that. Where do you see the hog market going, and what's driving that right now?</p>
<p>Newsom: Kind of a contrast to the cattle. You know, we don't have the support from the cash market right now. We've again just as in cattle, we've seen some herd liquidation, herd reports of early herd liquidation and this weighing on the cash price. We've seen a sluggish cash market and have hogs casting the previous lows. If we move through the lows, I think it's going to trigger another round of selling people, people just wanting out of the market, not just actual producers, but investors in the market. That's going to push the market over as well, and I don't know that the cash is strong enough to really provide that backbone of support that we are seeing in live cattle, so I think that we've got a bit more of a problem in the hogs.</p>
<p>Pearson: All right. Well, thank you so much, Darin. We appreciate you being here. That wraps up this edition of &quot;Market to Market.&quot; But if you&rsquo;d like more information from Darin on where these highflying markets just may be headed, visit the Market Plus page at our web site. You'll find expanded market analysis, audio podcasts, and streaming video of our program, as well as links to our Twitter Feed and Facebook account all free at the &ldquo;Market to Market&rdquo; website. Join us next week for a special edition of &ldquo;Market to Market.&rdquo; We&rsquo;ll assemble an expert panel to examine the impact of drought and explore strategies to lockin profits. Submit your questions at any of our social media sites this week and then join us for a special edition of &ldquo;Market to Market&rdquo; next week. Until then, thanks for watching. I'm Mike Pearson. Have a great week.</p>
<p id="p2">Copyright&copy; Iowa Public Television. All rights reserved. <a href="http://www.iptv.org/mtom/story.cfm/marketanalysis/9819/mtom_20120817_3751_marketanalysis" target="_blank">Original Article</a></p>
