

<p class="newsheader_t1">Food Safety News</p>
<p class="newssubhead_t1">Federal Egg Recall Investigation Widens</p>
<p>Federal officials are widening their investigation of two Iowa farms at the center of a large-scale egg recall and multistate Salmonella outbreak. The criminal division of the Food and Drug Administration and the Department of Justice have become involved in the effort, according to FDA Commissioner Dr. Margaret Hamburg.<br />
  <br />
  &quot;There is a formal investigation going on that extends beyond the FDA inspections that are focused on farm practice,&quot; Hamburg told reporters Wednesday. &quot;It is the case that an investigation is under way. We are pursuing it with our partners in law enforcement.&quot;</p>
<p>Both Wright County Egg and Hillandale Farms confirmed they were visited by a second round of federal investigators this week. The results from the first round of FDA inspection were made public Monday. </p>
<p>The reports illustrate widespread filth and food safety violations at both farms, but investigators have not determined how bacteria first entered the facilities. </p>
<p>The Des Moines Register also reported yesterday that FDA inspectors are investigating Central Bi-Products, a Minnesota-based rendering operation that supplies a feed ingredient, which tested positive for Salmonella, to Wright County Egg's feed operation. Though the bone meal produced by Central Bi-Products tested positive for a strain of Salmonella that matched the outbreak, FDA officials told reporters last week the feed could have become contaminated on-farm. </p>
<p>The ingredient was also handled by Superior Feed Ingredients in Waconia, Minnesota, before ultimately being supplied to Wright County. </p>
<p>Bone meal for feed is processed under high temperatures, a practice that should kill bacteria like Salmonella. </p>
<p>&quot;We believe that our product was free of all known pathogens after the cooking process and when it left our plants,&quot; Don Davis, president and CEO of Central Bi-Product's parent company, told The Des Moines Register, adding that his company periodically tests for the presence of bacteria.</p>
<p>Joshua Sharfstein, FDA's deputy commissioner, recently told reporters that, though the agency will take a thorough look at the feed contamination, there are &quot;multiple ways&quot; the feed could have become contaminated. &quot;It could actually just be part of the general contamination of these farms... While they have found it in the feed they are not concluding any kind of cause and effect relationships.&quot;</p>
<p>It is unclear whether the second round of investigation marks the beginning of a criminal probe. As Senator Chuck Grassley (R-IA) explained this week, the marketplace may deal more of a blow to Wright County Egg than federal regulators. </p>
<p>&quot;Unless they are doing something criminal or they are fined so little it doesn't hurt them, they can continue to do business,&quot; said Grassley this week, according to DTN/The Progressive Farmer.  &quot;I don't know to what extent the law says you can permanently put someone out of business.&quot;</p>
<p>&quot;But the marketplace is making the determination if the law doesn't and probably in this case, maybe the company may be hurt in the marketplace to the extent people are going to look and not buy eggs that have the word W-R-I-G-H-T in it,&quot; he said, adding that he believes the egg farms shouldn't produce food until the FDA determines the facilities are clean.</p>
<p>As far as not purchasing eggs bearing a &quot;Wright&quot; label, that may be tough for consumers at the retail level. The 550 million eggs recalled by Wright County and Hillandale this month were sold under more than a dozen different labels. </p>
<p>While some of the recalled product bears the &quot;Hillandale Farms&quot; name, consumers would have to look beyond a bevy of brand names--like Sunny Meadow, Glenview Farms, E&amp;M Ranch, Country Eggs, and Farm Fresh--to discover their eggs were in fact produced by Wright County Egg.</p>
<p>Wholesalers and supermarkets are in a better position to steer clear of either company if they're concerned. Food Democracy Now!, a grassroots sustainable agriculture organization, is launching a campaign to pressure grocery stores into banning Wright County Eggs after reports that the company's owner Austin &quot;Jack&quot; DeCoster has a long history of environmental, worker, and food safety violations.</p>
<p>It remains to be seen whether both companies will keep all their customers when they are given the go-ahead to sell shell eggs to consumers again. In the meantime, eggs from both farms are being diverted to &quot;breaker&quot; facilities where they are pasteurized for use in processed foods and other consumer goods. </p>
<p>Copyright&copy; Food Safety News. All rights reserved. <a href="http://www.foodsafetynews.com/2010/09/federal-egg-recall-investigation-widens/" target="_blank">Original Article</a></p>
