

<p class="newsheader_t1">Radio Iowa</p>
<p class="newssubhead_t1">Long range forecast looks good for farmers</p>
<p>Iowa farmers should be pleased with the latest long-range forecast. As the harvest gets underway, a meteorologist with D.T.N. says the weather the next couple of months should prove to be very good for agriculture. Bryce Anderson says the harvest began over the past week or two.</p>
<p>Anderson says the crops are so far along in their ripening and maturity rate that farmers will be able to get into the fields and &ldquo;really take care of business&rdquo; much earlier than last year. He predicts &ldquo;harvest is going to go quite well.&rdquo; Anderson says the overall weather picture is looking very favorable for Iowa&rsquo;s corn and soybean growers.</p>
<p>He says harvest will be starting during the final days of the official summer season and into early fall, so there will be longer daylight hours to work in, which a plus. As for rain, the weather patterns indicate there shouldn&rsquo;t be any major moisture systems setting up and settling in, at least for this section of the Corn Belt. Anderson says the majority of harvest could be completed by Halloween.</p>
<p>&ldquo;Producers are going to be able to get crops out of the field in good shape at a very acceptable level of moisture, so the driers aren&rsquo;t going to have to run nearly as much as they did last year,&rdquo; he says. He predicts the harvest should be wrapping up by the end of October, a big change from last year. Heavy rains late in 2009 turned many fields to muddy lakes, making harvest very difficult &mdash; and impossible in some areas. Some farmers had to leave crops over the winter to harvest early this year.</p>
<p>Copyright&copy; Radio Iowa. All rights reserved. <a href="http://www.radioiowa.com/2010/09/15/long-range-forecast-looks-good-for-farmers/" target="_blank">Original Article</a></p>
