

<p class="newsheader_t1">Telvent DTN</p>
<p class="newssubhead_t1">John Deere Agri Services and Telvent DTN announce agreement to add communications interfaces to AGRIS&trade; Commodity Management System</p>
<p>Alpharetta, Ga. &ndash; September 30, 2010 &ndash; John Deere Agri Services and Telvent DTN announce an agreement to develop communications interfaces for streaming Telvent DTN information into the AGRIS&trade; Commodity Management system. The interfaces will help agribusiness professionals using the AGRIS system reduce manual data entry of pricing information and contracts for completed offers, allow management of cash basis prices in one place, and simplify inventory valuation processes.</p>
<p>The interfaces will facilitate the transfer of Telvent DTN information to the AGRIS Commodity Management system in three areas: futures market and posted basis information from a DTN hosted website will populate prices on commodity contracts; updated futures and basis prices can be accessed for inventory valuation; and accepted offers from the DTN Grain Portal&trade; will import as contracts.</p>
<p>&quot;We see great benefit to our customers by reducing effort with the &quot;mark to market&quot; valuation process, improving contract pricing data integrity, and more efficiently managing offers in concert with Telvent DTN's agribusiness tools,&quot; says Allen Smith, senior product manager with John Deere Agri Services. &quot;Being able to automatically move completed offers as contracts into the AGRIS system will be a most welcome labor-saving feature,&quot; Smith adds.</p>
<p>&quot;The agriculture industry today is more volatile, complex and faster moving than ever before. In order to help agriculture professionals succeed during these challenging times, Telvent aims to provide its customers with the best tools and market data available,&quot; explains Telvent chief executive officer, Ignacio Gonz&aacute;lez. &quot;Our agreement with John Deere Agri Services provides agribusinesses with the ability to capitalize on market opportunities more effectively and increase the overall efficiencies of their operations.&quot;</p>
<p>The interfaces are currently planned for release in the fall of 2010. </p>
<p>For more information, call 1-800-393-8971 or send an e-mail to AgriServices@JohnDeere.com. Information about the AGRIS system can be found at www.JohnDeereAgriServices.com.</p>
<p>John Deere (Deere &amp; Company - NYSE: DE) is a world leader in providing advanced products and services for agriculture, forestry, construction, lawn and turf care, landscaping, and irrigation. John Deere also provides financial services worldwide and manufactures and markets engines used in heavy equipment. Since it was founded in 1837, the company has extended its heritage of integrity, quality, commitment, and innovation around the globe.</p>
<p>Copyright&copy; Telvent. All rights reserved. <a href="http://www.telvent.com/en/news_center/2010/John-Deere-Agri-Services-and-Telvent-DTN-announce-an-agreement-to-develop-communications-interfaces-for-streaming-Telvent-DTN-information-into-the-AGRIS-Commodity-Management-system.cfm" target="_blank">Original Article</a></p>
