

<p class="newsheader_t1">Journal-Advocate.com</p>
<p class="newssubhead_t1">Local students receive national degree</p>
<p>Sterling students, Mark Lieberknecht, Emily Mollohan, Hanna McKay, Stephanie Roth, Justin Bartlett and Joshua Sonnenberg received the American FFA Degree at the 83rd National FFA Convention in Indianapolis on Saturday, Oct. 23. It is the highest degree awarded by the National FFA Organization and recognizes their demonstrated leadership abilities and outstanding achievements in agricultural business, production, processing and service programs.<br />
  Less than one in 154 FFA members advance through their local chapter and state FFA degree programs to earn this national degree and this year the Sterling FFA Chapter had five recipients under the direction of their advisor, Dennis Wagner.</p>
<p>They all received a gold American FFA Degree key and a certificate in a blue leatherette frame to commemorate the achievement. The recognition program is sponsored by Case IH, DTN, Farm Credit, Pioneer, and Syngenta as a special project of the National FFA Foundation. The national FFA convention is the nation`s largest annual youth gathering, welcoming students, parents and educators from all across the United States.</p>
<p>The National FFA Organization, formerly known as Future Farmers of America, is a national youth organization of 523,309 student members (and counting) - all preparing for leadership and careers in the science, business and technology of agriculture - as part of 7,487 local FFA chapters in all 50 states, Puerto Rico and the Virgin Islands. The National FFA Organization changed to its present name in 1988 in recognition of the growth and diversity of agriculture and agriculture education. The FFA mission is to make a positive difference in the lives of students by developing their potential for premier leadership, personal growth and career success through agricultural education. The National FFA Organization operates under a Federal Charter granted by the 81st United States Congress, and it is an integral part of public instruction in agriculture. The U.S. Department of Education provides leadership and helps set direction for FFA as a service to state and local agricultural education programs.</p>
<p>Copyright&copy; Journal-Advocate.com. All rights reserved. <a href="http://www.journal-advocate.com/ci_16492376" target="_blank">Original Article</a></p>
