

<p class="newsheader_t1">Iowa Public Television</p>
<p class="newssubhead_t1">Market Analysis: Darin Newsom</p>
<p>Grain and oil seed prices were pressured this week with wheat prices leading the way.  For the week, December wheat gave back all of last week's gains and then some with a loss of nearly 50 cents, while the nearby corn contract moved more than 10 cents lower.  Soybeans followed the grains south as the January contract settled with a weekly loss of almost 70 cents, while nearby meal prices declined by more than $25 per ton.  In the softs, cotton broke through the $70 mark with a gain of $3.15 per hundred weight.  In the dairy market, December Class III milk futures lost 50 cents, while the deferred contract moved 40 cents lower.  Over in livestock, December cattle gained 40 cents, nearby feeders were off 15 cents and the December lean hog contract posted a weekly loss of 43 cents.  In the financials, the Euro gained 14 basis points against the dollar, crude oil lost 40 cents per barrel, Comex Gold declined by $16 per ounce and the Goldman Sachs Commodity Index shed nearly 3 points to settle at 637.40.</p>
<p>Pearson: Here now to lend us his insight on these and other trends is one of our regular market analysts, Darin Newsom.  Darin, welcome back.</p>
<p>Newsom: Good to be back, Mike.</p>
<p>Pearson: We're glad to have you here.  It's been a busy week.  I know you've been running ragged keeping track of everything that has happened.</p>
<p>Newsom: Right.</p>
<p>Pearson: Let's touch on some of the uncertainty that is going on in the broader market.  What is driving these selloffs?</p>
<p>Newsom: Yeah, you mentioned it in the opening sentence of tonight's program.  You had the word uncertainty and right now these markets are largely driven by investment sentiment and investors do not like uncertainty.  They do not like volatility.  They do not like the unknown.  And so what we're seeing from sector to sector, financials, energies, metals, grains, we're seeing these traders getting out of their positions and the effect on the market is regardless of fundamentals, regardless of supply and demand changes it is pushing the markets lower.</p>
<p>Pearson: How long is this going to continue?</p>
<p>Newsom: That's a great question because we can look at charts, we can look at any WASDE or USDA report that happens to come down the river.  Really it goes back to Newton, Newton's first law of motion.  I believe that a trending market will stay in that trend until acted upon by an outside force and that outside force has to be non-commercial trade or investment trade.  So until they change their mind we're going to see these trends continue.  Until some of this uncertainty is solved, until they get a better feel or a better -- wanting to stay in a market longer term it's just not going to happen.  We're going to continue to see this type of pressure until some sort of change occurs.</p>
<p>Pearson: And it's not the good kind of pressure we're in.  We're just going to keep trending downward.  Let's talk a little bit more specifically.  In the wheat market broad based selloff this week, down 50 cents in the nearby contract.  Is there anything specific we can attribute that to?</p>
<p>Newsom: Well, it's kind of a fun game to play in the wheat market watching headlines coming out of Ukraine.  One day they're going to limit or they're going to ban exports.  The next day they're going to be fine.  Then the next day they don't have any wheat to export anyway.  So it just goes back and forth and at this point wheat traders just simply don't care.  Then you've got the southern plains which is continued hot and dry or above normal temperature and continued dry situation.  That's not going away.  But all of these are known factors.  All of these are fundamentals that have been built in.  We don't know what's going to happen in Ukraine.  We don't know what's going to happen in Russia.  Yes they don't have the supplies and it should be just a matter of time before the U.S. starts to see some export demand pick up.  We know that the southern plains are going to have a difficult time with the hard red winter wheat but it's the fall and winter and we're not going to be concerned about it until it comes out of dormancy in the spring.  So all of these things are going to be shoved aside right now and markets perfectly content to move sideways until, again, something develops.</p>
<p>Pearson: And this sideways trade, what sort of prices are we trading between here do you think on wheat?</p>
<p>Newsom: Well, in the wheat market, hopefully I have my prices correct, the Chicago December was right around that $8.46 and we took that out.  Now, wheat is notorious for giving some sort of head fake, either going above resistance and then coming back down or below support and coming back up.  So what we're going to want to see is a sustained trade below some of these support levels and if it occurs then I think the market continues to drift down.  In the case of wheat, yeah, I think it's going to continue to come down a little bit because, again, it just doesn't have that short-term fundamental support to be able to push higher unless we see something major happen on the export side of the market.</p>
<p>Pearson: So for producers out there with some wheat left to sell what is your advice to them?  Do they try to sell here before we keep trending lower?  Or do you wait for that headline that is going to shock this market upwards?</p>
<p>Newsom: Most of the wheat has already been sold, just kind of the nature of the wheat market, the majority of it gets sold right off the combine or shortly thereafter and they don't wait around a long time to clean out the bins.  Now, what wheat is being held, I hate to sell it in a hole like this.  There is the chance for a rally at some point but seasonally the market does trend lower through November.  So I think if you get a bounce back and you're just comfortable letting go and moving on worrying about other things, maybe worrying about next year's crop the yes, I think you go ahead and just let go of the wheat.</p>
<p>Pearson: All right.  Well let's move to the other biggest mover this week in soybeans.  We've seen another round of liquidation in soybeans all week long.  Same story in soybeans?</p>
<p>Newsom: It is, even more dramatic than wheat and actually it's more dramatic than what we've seen in most markets because this is a market where long-term fundamentals are still quite bullish.  You could still make the argument that by the end of February, mid-March globally we're going to be out of soybean stocks and we've got excellent export demand going on right now from the United States yet the market continues to freefall.  Why is that?  Well, CFTC report this week showed another 30,000 contracts or roughly about 28,000, 29,000 contracts liquidated again from the non-commercial position.  This has been an ongoing thing since July, it continues to gain momentum.  We've now seen more than 33 percent of their overall position liquidated since that timeframe.  Fundamentally there's no reason for the market to go down.  But, again, let's go back, it's not going to change its trend until these investors change their mind.   Yes we've seen some rain develop.  Yes we've got some better growing conditions now in South America.  But that still isn't going to affect the market until say mid-March when those crops start to come in.</p>
<p>Pearson: In the meantime are there price levels out there that producers could watch for, guidance, any signs of support that you are tracking?</p>
<p>Newsom: I've looked at this from a technical point of view and right now you can kind of throw some numbers out there.  We've got some retracement support around $13.77.  That is a retracement of the previous uptrend.  We've got a trend line support right around $13.72.  If these -- these are in the January contract and if these price levels don't hold market could come back to $13.40 down in $13.40, $13.41 level.  Longer term could we see it even go lower than that?  Some have tried to make that argument.  But, again, it just comes back to fundamentals.  If at some point the fundamentals or supply and demand come back into play it should provide support to soybeans.</p>
<p>Pearson: So here in the soybean market advice to producers might be hold on through this downward patch and wait a little bit longer?</p>
<p>Newsom: Yeah because it's still a market that I'm longer term bullish on.  Yes we're talking about an 81 million metric ton production in Brazil, 55 million metric ton production in Argentina but that's a long way down the road.  So I still think we can see this market come back.  The cash market remains firm, basis continues to look strong, so I think this market could come back.  It's just going to have to find some level down here where investors start to buy because we've got commercial buying already coming in, investors are just going to have to get interested in this market again at some point.</p>
<p>Pearson: So producers wait?</p>
<p>Newsom: If you're going to hold a crop I think you could hold the soybean crop without -- the risk/reward right now seems to be in favor of holding it.</p>
<p>Pearson: All right.  Let's talk corn a little bit.  We had another selloff in corn.  Same story going on there.  Do you see this continuing in the same vein as wheat and beans?</p>
<p>Newsom: The corn market has been pretty quiet.  We've trended sideways now for quite some time.  Only here the last couple of weeks have we tried to dip down a little bit. We pushed through support, technical support in the December contract at $7.15 on Friday, bounced back with the news out of EPA and the more I thought about this EPA news, my initial knee jerk reaction was, okay, this is bullish but maybe not long-term.  I think long-term this is going to keep the question of are we killing off this demand market because the weather situation has not improved going into the winter, it's not really expected to improve by next spring and so coming out of the drought of 2012 and facing another dry situation in 2013 we could be looking at another tight situation in corn next year and that means continued pressure on no exports, continued cutback in feed demand.  This may not be the recipe that we want to start to rebuild demand in the corn market.</p>
<p>Pearson: And that raises an interesting point for producers out there who are thinking about selling next year's crop.  If your scenario takes place where we do continue to kill off feed demand and export demand would it make sense for producers to begin selling next year's crop at the prices that are out there currently?</p>
<p>Newsom: This is a real coin toss because early estimates out there right now are 97 to 98 million acres.  That's a huge number.  So if we have ideal weather and we get the type of production -- we're not going to get anywhere close to trend line.  I think trend line yield is a farce anyway.  But we're not going to get close to what is being projected right now.  But if we see better yield next year, if the weather helps we're going to have a great deal of supply and that means if we haven't brought demand back -- and it's going to take a while to get that demand back -- we could be looking at rebuilding our surplus of corn.  So there's a lot of ifs in that statement.  If a lot of that doesn't happen we're going to be looking at just as explosive of a market in 2013, 2014 as we did here in 2012, 2013.</p>
<p>Pearson: So it is a coin flip.</p>
<p>Newsom: It is a coin flip.  I mean --</p>
<p>Pearson: There's risk and reward on either side.</p>
<p>Newsom: And the December contract is well below what we're seeing for these old crop contracts so it's not saying it just really wants to be sold right now but let's say we see the old crop move up, let's say we are able to build some momentum going forward into the winter I think then at some point we are going to want to pull the trigger on a little bit of our next year's production keeping a very close eye though on weather developments.</p>
<p>Pearson: All right.  I'd like to talk a little bit about cotton.  We saw a bit of a move this week up $3.15.  What is driving that?</p>
<p>Newsom: Well, that was an interesting move.  We've got all these markets where investment traders are getting out.  I think they finally decided they have beaten the cotton market up enough because fundamentally you look at the global fundamentals of the cotton market it looks relatively bearish.  Now the new crop cotton market you can almost make a bit more of a bullish argument because if there's going to be a crop that loses acres it's going to be cotton.  You're going to expect to see acres increase in wheat, soybeans and corn and most of that is going to come at the cost of cotton.  So we're finally starting to see a little bit of buying come back in but the global picture is still so bearish I think it's going to be limited on how much upside momentum we can build.</p>
<p>Pearson: All right.  Let's talk livestock a little bit.  Where do you see feeder cattle headed in the near term?</p>
<p>Newsom: I don't look for feeder cattle to do a lot.  I think both feeder cattle and live cattle are trapped in here right now so similar to what we're seeing in the corn market with a lot of sideways trends going on.  Much of it could depend on the type of, again, the type of winter that we have but I wouldn't be anticipating a huge move in either direction either feeder or live cattle say over the next couple of months.  I think they're going to kind of wait to see, feel things out a little bit, see what type of winter develops and then move the market from there.</p>
<p>Pearson: The cattle on feed report did come out today.  Were there any surprises in there that you think is going to have any effect here next week?</p>
<p>Newsom: I haven't been hearing a lot of talk about what is going to happen in the market next week so I would not be anticipating -- we've got kind of a holiday chopped up week next week, it could raise the volatility a little bit but I'm not hearing a great deal of reaction to this afternoon's report or Friday afternoon's report.</p>
<p>Pearson: People were expecting lower placements and lower marketings and that's what they got.</p>
<p>Newsom: That's pretty much what they got this time around.</p>
<p>Pearson: All right.  Now as we move into holiday season where do you see hogs going?</p>
<p>Newsom: Hogs have been interesting for quite some time.  They have been needing to build some cash support and we have actually got some commercial buying coming in.  We've had a very nice little run up in the hog market.  I think as we head into the holiday timeframe here this could continue.  Hogs just seem to be building some support.  Now, hogs being hogs it can disappear in a flash.  We've seen that happen so many times.  But I would anticipate as we look at the Dec and the Feb contracts I think this market could start to really build some momentum in here, could keep this rally that we've seen going and if anything does start to help support the live cattle we do know that we're dealing with tighter supplies.  You add in the hog market and I think both could start to build maybe a little bit of momentum later on this winter.</p>
<p>Pearson: All right.  So perhaps some bullish news out there for producers.</p>
<p>Newsom: Yeah, we have to take it with a grain of salt because it is hogs and they can change their mind so quickly.</p>
<p>Pearson: All right.  One of the things you mentioned a little bit earlier when we were talking in the grains, you mentioned the non-commercial interest in the grain market that we saw grow exponentially over the summer.  Where are those non-commercials now?  And what effect is that having on the market?</p>
<p>Newsom: Well, you talked about how all the three major stock indexes were down, NASDAQ, the Dow and so on.  We've got money coming out of the Dow.  We've got money coming out of the grains.  We've got money coming out of commodities in general.  To me it looks like it's a movement to cash right now.  We've got support coming into the U.S. dollar index, there's more talk that the Federal Reserve is going to raise the fed fund rate probably at some point in 2013, you've got the problems going on in Europe.  I think, again, we go back to this question of uncertainty, investors just don't want to be in &quot;traditional&quot; positions right now and so they're going to move off into cash, they're going to move off into the U.S. dollar, they're going to look for something to play this interim until things calm down a little bit.</p>
<p>Pearson: And how long can they afford to have all those dollars in cash?  Is this something we could see for six weeks?</p>
<p>Newsom: Most of them have had -- I haven't seen the numbers yet but I would anticipate many of these funds have had a pretty decent year depending on when they got into the markets and how slow they were in reacting once these things turned.  So they may be willing to sit out through the end of this year, see what happens with all of the U.S. economic talk going on through the December 31st, see where we are at that point and then maybe start looking for those markets with fundamentals.</p>
<p>Pearson: Great.  Thank you so much, Darin.  That wraps up this edition of Market to Market.  But if you'd like more information from Darin on where these markets just may be headed visit the Market Plus page at our website.  You'll find expanded market analysis, audio podcasts and streaming video of our program as well as links to our Twitter feed and Facebook accounts all free at the Market to Market website.  Be sure to join us next week when we'll examine efforts to keep Asian carp out of Midwest waterways.  Until then, thanks for watching.  I'm Mike Pearson.  Have a great week.</p>
<p id="p2">Copyright&copy; Iowa Public Television. All rights reserved. <a href="http://www.iptv.org/mtom/story.cfm/marketanalysis/10039/mtom_20121116_3812_marketanalysis" target="_blank">Original Article</a></p>
