

<p class="newsheader_t1">AgFax.com</p>
<p class="newssubhead_t1">A Wet Growing Season Makes as Much as a Quarter of the Canadian Wheat Crop Feed Quality</p>
<p>Because of a wet growing season, as much as a quarter of the Canadian wheat crop is feed quality this year -- the most in six years, reported the Canadian Wheat Board. Based on USDA's November estimate of a 22.2-million-metric-ton 2010-11 Canadian crop, that means as much as 5.55 mmt might be feed quality. This compares with 2.25 mmt fed from the 2009-10 crop and 3.3 mmt from the 2008-09 crop.</p>
<p>In an average year, more than 70 percent of Canada's Prairie spring wheat makes the top two grades, the CWB reported. This year, only 38 percent is expected to grade No. 1 or 2, leaving about 35 percent as No. 3 and 25 percent as feed. Not since the cold summer and wet harvest of 2004 has the CWB expected such a high volume of feed wheat.</p>
<p>However, this is no surprise to the market, cautioned University of Minnesota grain marketing economist Edward Usset. &quot;The wheat is in the bin, and the trade likely has known the quality concerns for some time.&quot; In fact, some in the trade believe commercials have covered much of their needs.</p>
<p>DTN Analyst John Sanow also doubts it will have much market impact going forward: &quot;I don't know how inclined cattle feeders are to make a switch to feed wheat, or what price differential it would take to make that change,&quot; said Sanow. &quot;But I find it hard to believe 5.5 mmt will make a big difference in the grand scheme of things.&quot;</p>
<p>The current spread between July wheat and July corn is about $1.64, so corn will have to get a lot higher or July wheat will have to fall to narrow that spread to encourage wheat feeding, noted Jerry Gulke of the Gulke Group, a DTN premium information source. &quot;Old timers say a 80 cent differential works.&quot;</p>
<p>If comparative prices adjust to favor Canadian feed-quality wheat crossing the border, it will be welcomed in the feeding sector, said Kim Anderson, Oklahoma State University Extension economist. &quot;Tight corn stocks are not only keeping corn prices firm, but the value of feed wheat -- in essence, setting a higher floor. Greater availability of feed wheat may moderate the upside somewhat, but I don't expect a big impact.&quot;</p>
<p>Anderson believes the lower-quality wheat crop in Canada might boost wheat protein premiums if the market hasn't already fully adjusted. &quot;Typically, buyers blend high-protein Canadian hard red spring wheat to boost protein values. Lack of that supply may boost the protein premium for milling-quality U.S. hard red winter wheat,&quot; he explained.</p>
<p>Longer term, and perhaps most importantly, Anderson said, &quot;This widens the opening for 2011—12 wheat prices. It sets the stage for much higher prices if we don't have an above-average crop.&quot;</p>
<p>Sanow agreed: &quot;With excessive dryness in the western Plains, too much moisture in parts of Australia and concern with production in Russia and the Black Sea Region, world supplies could indeed shrink further in 2011.&quot;</p>
<p>Usset added that U.S. wheat exporters have already stepped into the export breach created by the Russian crop disaster as well as the reduced availability of high-quality Canadian wheat.</p>
<p>To better serve farmers who have feed wheat to market, the CWB has launched an early pricing option for western feed wheat (www.cwb.ca/epo). Farmers can lock in values equal to 80 percent to 200 percent of the pool-return outlook, depending on whether farmers expect prices to rise or fall before they deliver the wheat. CWB cautions producers to price only the amount of wheat they are sure they can deliver because if they have a shortfall, the remainder of the contract can be transferred to another producer or can be bought out, but that could be &quot;quite expensive.&quot;</p>
<p class="newssubhead_t1">&nbsp;</p>
<p>Copyright&copy; AgFax.com. All rights reserved. <a href="http://agfax.com/Content/canadian-wheat-feed-11302010.aspx" target="_blank">Original Article</a></p>
